### ISSUE TITLE
hasOneDeep 

### ISSUE THREAD

**Issue by zymawy** [staudenmeir/eloquent-has-many-deep#10]
Nice Packages @staudenmeir,

I have an issue. 
having following tables
`country table`

id | name | code
------------ | ------------- | ----------
int | string | string

`city table`

id | country_id | name
------------ | ------------- | ----------
int | int | string

`University  table`

id | city_id | name | other_columns
------------ | ------------- | ---------- | ---------
int | int | string | type

I'm Filtering According To The Country And Other Column On The `University Table`.
The Issue Here Is `University table` only has`city_id` but I Want Use `University table` instead of the `city table` How I can acheive that with `hasOneDeep`

**Comment by staudenmeir** [comment]
Can you provide parts of your code? What does your query look like?

How exactly do you want to filter the results?

**Comment by zymawy** [comment]
Hi @staudenmeir , 

I'm Working This [Package](https://github.com/Tucker-Eric/EloquentFilter). 
That Can Help Me To Filter In Mult Column In Different Tables. 

Giving I have `Query String Url`
`http://alkhirat.org/search?country=nigeria&major=software-engeenring&degreeType=master`
I Want To FIlter The Universities According To This `Query_String`
`University Table` Does Not Have Relation With `Country Table` 
It Has Relation With `City Table`
I Want To Make I Relation In `University Table`
So That I Can Filter Throw It

Here Is The `country` Relation In `University Table`
```php
    public function country()
    {
        return $this->hasOneDeep(
            Country::class,
            [City::class]
        );
    }
```

No Luck So Far. 

Thank You, An Advanced

**Comment by staudenmeir** [comment]
`HasOneDeep` is not the right relationship in this case, you would use it for the opposite direction.

Take a look at the `BelongsToThrough` package: https://github.com/znck/belongs-to-through

**Comment by zymawy** [comment]
Nice, Wouldn't Be Nice If You Implement [belongs-to-through]( https://github.com/znck/belongs-to-through). In Your Fabulous Package?

**Comment by staudenmeir** [comment]
I have no plans for this at the moment.

**Comment by zymawy** [comment]
Okay,

Thank You. ❤️
