### ISSUE TITLE
hasManyThrough with Many-To-Many

### ISSUE THREAD

**Issue by gilvaju** [staudenmeir/eloquent-has-many-deep#100]
![image](https://user-images.githubusercontent.com/677039/95390440-c9165780-08cb-11eb-89e3-8e4065a3d72e.png)

I`m have many to many relationship between Material and SheetGroup.
Also, Sheet and SheetGroup with One to many.

`
Sheet->groups - work!
SheetGroup->sheet - work!
Material->groups - work
SheetGroup->materials - work
`

I would like something like

`
material->groups->sheet
`

https://laravel.com/docs/8.x/eloquent-relationships#has-many-through

I found this relationship in laravel docs, but I think it only works with a one to many relationship.

**Comment by nessor** [comment]
how about sth. like this? 

```php
//In class material
public function sheet(){
  return $this->hasManyDeepFromRelations($this->groups(), (new SheetGroup)->sheet());
}
```

**Comment by gilvaju** [comment]
Awesome, i will try and return here. Thank you so much!
