### ISSUE TITLE
Help with belongsToMany and belongsToMany

### ISSUE THREAD

**Issue by Ruchira0893** [staudenmeir/eloquent-has-many-deep#101]
Hello,

Thank you for such an amazing library, I have been using it for a while and got stuck with this relational structure:

I have **Group** which is in  `belongsToMany` with **ConstructionProduct** which is `belongsToMany` with **Project**

My model looks something like this:

	class Group extends Model
	{

		public function constructionProduct()
		{
			return  $this->belongsToMany(ConstructionProduct::class,'construction_product_details',
				'product_group_id', 'construction_product_id');
		}

	}

	class ConstructionProduct extends Model {

		public function projects()
		{
			return $this->belongsToMany(Project::class,'construction_product_projects','construction_product_id','project_id');
		}

	}

My relationship looks like:

    public function projects()
    {
        return $this->hasManyDeep(
            Project::class,
            ['construction_product_details', ConstructionProduct::class, 'construction_product_projects'],
            ['product_group_id', 'construction_product_id', 'id'],
            ['id', 'construction_product_id', 'project_id']
        );
    }

>Error: Unknown column 'construction_product.project_id

Help me out with this. Thanks.

**Comment by staudenmeir** [comment]
Please try this relationship:

```php
public function projects()
{
    return $this->hasManyDeep(
        Project::class,
        ['construction_product_details', ConstructionProduct::class, 'construction_product_projects'],
        ['product_group_id]
    );
}
```

**Comment by Ruchira0893** [comment]
Thanks, it worked. One more doubt how to execute `belongsToMany` to `belongsTo` to `belongsToMany` relationships:

I have **Brand** which is in  `belongsToMany` with **ConstructionProductDetails** which is `belongsTo` with **ConstructionProduct** which is in  `belongsToMany` with **Project**

My model looks something like this:

class Brand extends Model {

 
    public function constructionDetails()
    {
        return $this->belongsToMany(ConstructionProductDetails::class, 'construction_product_brands', 'brand_id', 'const_product_details_id');
    }

}

class ConstructionProductDetails extends Model {

    public function constructionProduct()
    {
        return $this->belongsTo(ConstructionProduct::class, 'construction_product_id', 'id');
    }

}

class ConstructionProduct extends Model {
    public function projects()
    {
        return $this->belongsToMany(Project::class,'construction_product_projects','construction_product_id','project_id');
    }
}

Help me out with this. Thanks.

**Comment by staudenmeir** [comment]
Have you tried https://github.com/staudenmeir/eloquent-has-many-deep#existing-relationships?

**Comment by Ruchira0893** [comment]
I have tried this out but didn't get the expected result.

I tried like this:

	class ConstructionProductDetails extends Model {

		public function projects()
		{
			return $this->hasManyThrough(ConstructionProduct::class, Project::class);
		}
	}

	class Brand extends Model {

		public function constructionDetails()
		{
			return $this->belongsToMany(ConstructionProductDetails::class, 'construction_product_brands', 'brand_id', 'const_product_details_id');
		}
		
		
		//Relation I tried.
		public function projects()
		{
			return $this->hasManyDeepFromRelations(
				$this->constructionDetails(), (new ConstructionProductDetails())->projects()
			);
		}
		
	}

I'm unable to get the desired result.

**Comment by staudenmeir** [comment]
> I'm unable to get the desired result.

Are you getting an error?

**Comment by Ruchira0893** [comment]
No, but I'm getting projects count = 0 for each brand.

**Comment by staudenmeir** [comment]
How are you using the `projects` relationship in your query?

**Comment by Ruchira0893** [comment]
Hi, sorry for late response, I'm using `projects_count` with **Brand** Model like this:

	$brands = Brands::withCount(['projects' => funtion ($q) {
			//some logic over here....
		}])->get();

Whenever I'm trying to fetch projects_count I find it to be null/0.

**Comment by staudenmeir** [comment]
What do you get when replacing `->get()` with `->toSql()`?

**Comment by Ruchira0893** [comment]
>
"select `brands`.*, (select count(*) from `projects` inner join `construction_product_projects` on `construction_product_projects`.`project_id` = `projects`.`id` inner join `construction_product` on `construction_product`.`id` = `construction_product_projects`.`construction_product_id` inner join `construction_product_details` on `construction_product_details`.`id` = `construction_product`.`id` inner join `construction_product_brands` on `construction_product_brands`.`const_product_details_id` = `construction_product_details`.`id` where `construction_product`.`deleted_at` is null and `construction_product_details`.`deleted_at` is null and `brands`.`id` = `construction_product_brands`.`brand_id` and `projects`.`status` = ? and exists (select * from `construction_product` inner join `construction_product_projects` on `construction_product`.`id` = `construction_product_projects`.`construction_product_id` where `projects`.`id` = `construction_product_projects`.`project_id` and `status` = ? and `construction_product`.`deleted_at` is null) and (`tracked` = ?) and `construction_product`.`deleted_at` is null and `construction_product_details`.`deleted_at` is null and `projects`.`deleted_at` is null) as `projects_count` from `brands` where `brands`.`deleted_at` is null"

**Comment by staudenmeir** [comment]
Sorry, I somehow didn't get a notification for your comment. Is the issue still open?
