### ISSUE TITLE
Group → hasMany Students → belongsToMany Parents

### ISSUE THREAD

**Issue by jozeflambrecht** [staudenmeir/eloquent-has-many-deep#104]
Hi, I want to send messages to all the parents of students that belong to a group (class).
I am having trouble by setting the local and foreign keys:
my tables
**Group**
id
name

**Student**
id
group_id

**parent_student**
parent_id on users
student_id on students

What I tried:
```
    /**
     * Get all of the parents for the group.
     */
    public function parents()
    {
        return $this->hasManyDeep(User::class, [Student::class, 'parent_student'], ['group_id', 'parent_id', 'id'], ['student_id', 'id', 'group_id']);
    }
```
The result is an empty collection, but I do have students with linked parent accounts... Someone can please assist?

**Comment by jozeflambrecht** [comment]
This workaround does "the job", but is not efficient..
```
        $parents = collect();
        $this->students->each(function ($student) use ($parents) {
            foreach ($student->parents as $parent) {
                $parents->push($parent);
            }
        });
        return $parents;
```

**Comment by staudenmeir** [comment]
Use this relationship:

```php
public function parents()
{
    return $this->hasManyDeep(
        User::class,
        [Student::class, 'parent_student'],
        ['group_id', 'parent_id', 'id'],
        ['id', 'id', 'student_id']
    );
}
```

**Comment by jozeflambrecht** [comment]
hi Jonas, thanks for helping me! I tried your solution, but it returns again an empty collection (no error message). The Student model is using a Uuid, I don't know if that can be the problem..

**Comment by staudenmeir** [comment]
How are you using the relationship in your query?

**Comment by jozeflambrecht** [comment]
I want to send a notification to all parents of a group:  `Notification::send($group->parents, new NewMessage($message));`

Also when I test with tinker:
```
$ php artisan tinker
Psy Shell v0.10.4 (PHP 7.4.4 — cli) by Justin Hileman
>>> $group = App\Group::findOrFail(1);
=> App\Group {#4386
     id: 1,
     name: "Maternelle A",
     grade_id: 2,
     created_at: "2020-08-04 08:58:52",
     updated_at: "2020-09-10 12:09:55",
     deleted_at: null,
     teacher_id: 3,
   }
>>> $group->parents
=> Illuminate\Database\Eloquent\Collection {#4394
     all: [],
   }
```

**Comment by jozeflambrecht** [comment]
Some more info:

In App\Group.php
```
    /**
     * Get the students for the class.
     */
    public function students()
    {
        return $this->hasMany('App\Student')->orderBy('last_name');
    }
```
Student.php
```
    public function parents()
    {
        return $this->belongsToMany(User::class, 'parent_student', 'student_id', 'parent_id');
    }
```

**Comment by staudenmeir** [comment]
Have you tried the query in an application (outside of tinker)?

**Comment by jozeflambrecht** [comment]
yes, just tried `Notification::send($group->parents, new NewMessage($message));` and no notifications were sent to the parents 😞

**Comment by jozeflambrecht** [comment]
Got it working!
```
        return $this->hasManyDeep(
            User::class,
            [Student::class, 'parent_student'],
            ['group_id', 'student_id', 'id'],
            ['id', 'id', 'parent_id']
        );
```

I switched student_id and parent_id. I guess because of the naming.. I am using parent_student instead of student_user (alphabetical order)

**Comment by jozeflambrecht** [comment]
Thanks @staudenmeir for your package and support!
