### ISSUE TITLE
Access table through pivot

### ISSUE THREAD

**Issue by GMounir** [staudenmeir/eloquent-has-many-deep#106]
I have this schema, how i can access it 
Admins -> packages -> package_unit -> units
**admins**:
id, ...

**packages**:
id, admin_id,...

**package_unit**:
package_id, unit_id

**units**: 
id, ...

**access it from admin just like this**
**_admin->units_**

**Comment by staudenmeir** [comment]
Use this relationship:

```php
class Admin extends Model
{
    use \Staudenmeir\EloquentHasManyDeep\HasRelationships;

    public function units()
    {
        return $this->hasManyDeep(Unit::class, [Package::class, 'package_unit']);
    }
}
```
