### ISSUE TITLE
hasManyDeepFromRelations and belongsToMany

### ISSUE THREAD

**Issue by shelestovas** [staudenmeir/eloquent-has-many-deep#109]
Hi!
Thank you for the super package, I solved a lot of problems with it)But there was another one that I didn't understand how to solve yet

`<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Staudenmeir\EloquentEagerLimit\HasEagerLimit;
use Staudenmeir\EloquentHasManyDeep\HasRelationships;

class EduLevelType extends Model
{
    use HasRelationships;
    use HasEagerLimit;

    public function eduLevels()
    {
        return $this->hasMany(EduLevel::class);
    }

    public function specialities()
    {
        // EduLevelType hasMany EduLevel -> EduLevel hasMany Direction -> Direction hasMany Speciality
        return $this->hasManyDeep(
            Speciality::class,
            [
                EduLevel::class,
                Direction::class
            ]
        );
    }

    public function professions()
    {
        // EduLevelType hasMany EduLevel -> EduLevel hasMany Direction -> Direction hasMany Speciality -> Speciality belongsToMany Profession
        return $this->hasManyDeepFromRelations($this->specialities(), (new Speciality)->professions());
    }
}
`

in controller:

`
        $allCounts = EduLevelType::withCount([
            'specialities',
            'professions'
        ])
            ->get();
`
This works, but profession counts based on an intermediate table "profession_speciality", but need to use the "professions" table

![studika localhost - Google Chrome](https://user-images.githubusercontent.com/12628413/102063335-f5d47700-3e06-11eb-814c-48a620208025.jpg)
![MySQL Workbench1](https://user-images.githubusercontent.com/12628413/102063342-f705a400-3e06-11eb-95d1-7e62bbe9e840.jpg)
![MySQL Workbench](https://user-images.githubusercontent.com/12628413/102063343-f79e3a80-3e06-11eb-90c3-2eaafdea7d30.jpg)

**Comment by staudenmeir** [comment]
What does `Speciality::professions()` look like?

**Comment by shelestovas** [comment]
`
public function professions()
    {
        return $this->belongsToMany(Profession::class);
    }
`

**Comment by shelestovas** [comment]
so far I have solved the problem this way

`
$counts = EduLevelType::withCount([
            'specialities',
            'professions' => function ($query) {
                $query->select(DB::raw('count(distinct professions.id)'));
            }
        ])
            ->get();
`

**Comment by staudenmeir** [comment]
Can you log the executed SQL?

**Comment by shelestovas** [comment]
Without `$query->select(DB::raw('count(distinct professions.id)'));`

```
SELECT 
    `edu_level_types`.*,
    (SELECT 
            COUNT(*)
        FROM
            `specialities`
                INNER JOIN
            `directions` ON `directions`.`id` = `specialities`.`direction_id`
                INNER JOIN
            `edu_levels` ON `edu_levels`.`id` = `directions`.`edu_level_id`
        WHERE
            `edu_level_types`.`id` = `edu_levels`.`edu_level_type_id`) AS `specialities_count`,
    (SELECT 
            COUNT(*)
        FROM
            `professions`
                INNER JOIN
            `profession_speciality` ON `profession_speciality`.`profession_id` = `professions`.`id`
                INNER JOIN
            `specialities` ON `specialities`.`id` = `profession_speciality`.`speciality_id`
                INNER JOIN
            `directions` ON `directions`.`id` = `specialities`.`direction_id`
                INNER JOIN
            `edu_levels` ON `edu_levels`.`id` = `directions`.`edu_level_id`
        WHERE
            `edu_level_types`.`id` = `edu_levels`.`edu_level_type_id`) AS `professions_count`
FROM
    `edu_level_types`
```

**Comment by staudenmeir** [comment]
Can you provide a database dump with the actual data or some sample data?
