### ISSUE TITLE
HasManyDeep, SoftDeletes and ambiguous column deleted_at

### ISSUE THREAD

**Issue by stefnats** [staudenmeir/eloquent-has-many-deep#113]
Hey,

first thanks for this amazing package. It saved me a lot of time and makes my code so much better to read.

I have a problem with the `hasManyDeep` relationship. In my `Post` model i have this relationship:

```php
public function comments() {
    return $this->hasManyDeep(Comment::class, [User::class, Post::class]);
}
```
(these are just placeholder to obfuscate the real code)
This results in a query like

```sql

select "comments".*, "users"."post_id" as "laravel_through_key" 
from "comments" 
inner join "posts" on "posts"."id" = "marketplace"."post_id" 
inner join "users" on "users"."id" = "posts"."user_id" 
where "posts"."deleted_at" is null and "deleted_at" is null and "users"."post_id" = 3 and "comments"."id" in (21) and "comments"."deleted_at" is null
```

The problem here is that the second where condition states `deleted_at is null` which results in this error:

```
SQLSTATE[HY000]: General error: 1 ambiguous column name: deleted_at
```

Please note that all three models are using Soft Deletes.

Is there something that i'm doing wrong or is this a bug?

**Comment by staudenmeir** [comment]
What versions of Laravel and the package are you using?

What query are you executing to get this SQL?

**Comment by stefnats** [comment]
Hey,

this package version 1.13.1
Laravel 8.28.1

I'm just lazy loading the relation.

Hope that helps detecting the cause?!

**Comment by stefnats** [comment]
Oh man... So this is a bug caused by me.

I used `SoftDeletes` that i accidentally imported from the `Jenssegers\Mongodb\Eloquent\SoftDeletes` Package. Yup, i'm also using `jenssegers/laravel-mongodb`.
Shame on me, issue closed. ;)
