### ISSUE TITLE
hasMany → belongsToMany relation

### ISSUE THREAD

**Issue by bastienu** [staudenmeir/eloquent-has-many-deep#115]
Hi,

Sorry, I'm pretty sure I did not read correctly the documentation... but I can't find my case.

Here is my relationships :
`Information` → has many → `Content` → belongs to many → `Source`
And I want to get my sources from an information, of course.

I have tried this:
```php
class Content extends Model 
{
    public function sources()
    {
        return $this->belongsToMany(Source::class);
    }
}



class Information extends Model 
{
    use \Staudenmeir\EloquentHasManyDeep\HasRelationships;

    public function contents()
    {
        return $this->hasMany(Content::class);
    }

    public function sources()
    {
        return $this->hasManyDeep(Source::class, [ Content::class ]);
    }
}
```

But I get the following error: `Undefined column: 7 ERROR:  column sources.content_id does not exist`, and it's totally normal because contents and sources are linked through a pivot table named "content_source".

So, what am I missing?

Thanks for your help :-)

**Comment by staudenmeir** [comment]
Use this relationship with the additional pivot table:

```php
class Information extends Model 
{
    use \Staudenmeir\EloquentHasManyDeep\HasRelationships;

    public function sources()
    {
        return $this->hasManyDeep(Source::class, [Content::class, 'content_source']);
    }
}
```

**Comment by bastienu** [comment]
Thanks a lot, it's working !

And sorry again, but for the inverse relation, from Source to Information with the following 
Source → belongsToMany → Content → belongsTo → Information ? 

```php
class Source extends Model 
{
    use \Staudenmeir\EloquentHasManyDeep\HasRelationships;

    public function rss_informations()
    {
        return $this->hasManyDeep(RssInformation::class, ??);
    }
}
```

I tried to follow the documentation and the Laravel doc, but anything was correct... :-(

**Comment by staudenmeir** [comment]
Use this relationship:

```php
class Source extends Model 
{
    use \Staudenmeir\EloquentHasManyDeep\HasRelationships;

    public function rss_informations()
    {
        return $this->hasManyDeep(
            RssInformation::class,
            ['content_source', Content::class],
            [null, null, 'id'],
            [null, null, 'information_id'] // "rss_information_id"?
        );
    }
}
```

**Comment by bastienu** [comment]
Perfect, it's working ! Thanks a lot :-)

**Comment by bastienu** [comment]
Hi,

I'm sorry, I'm reopening this issue, because it's going more and more complicated...
Everything was working but I changed the way on storing some information, and I have now a morphedByMany relationship.

Up to this morning, the relationship was:
Flux → belongsToMany → (App\Models\)RssContent → belongsTo → RssInformation

And this relationship was working very well:
```php
class Flux extends Model 
{
    use \Staudenmeir\EloquentHasManyDeep\HasRelationships;

    public function rss_informations()
    {
        return $this->hasManyDeep(
            RssInformation::class,
            [ 'flux_rss_contents', RssContent::class ],
            [null, null, 'id'],
            [null, null, 'rss_information_id']
        );
    }
}
```


But now, here is the new relationships :
Flux → morphedByMany → (App\Models\)RssContent → belongsTo → RssInformation
The morphedByMany pivot table is named "flux_contents".

To can you help to get this work ? I can't find how myself :-(

Sorry to disturb again...

**Comment by bastienu** [comment]
Sorry, I did not read correctly the documentation.
Everything OK now, thanks and sorry !
