### ISSUE TITLE
Eager Loading

### ISSUE THREAD

**Issue by bedoz** [staudenmeir/eloquent-has-many-deep#116]
Hi everyone, i found this package very interesting, i'm not tried it yet, but I have one question.
What about eager loading? Is it already implemented or it will be done in future?

This helped me a lot to reduce query on page and given the complexity of cascade relationships and their possible use in a cycle, it would certainly reduce the load as much as possible.

Thank you very much and nice job.

I'll give it a try for sure ASAP.

**Comment by staudenmeir** [comment]
Eager loading is implemented.
