### ISSUE TITLE
what's the foreignKeys and localKeys when ManyToMany → ManyToMany ?

### ISSUE THREAD

**Issue by hugsycms** [staudenmeir/eloquent-has-many-deep#117]
In the docs, we can see: 

#### ManyToMany → ManyToMany

Consider the [documentation example](https://laravel.com/docs/eloquent-relationships#many-to-many) with an additional `ManyToMany` level:  
`User` → many to many → `Role` → many to many → `Permission`

Add the pivot table to the intermediate models:

```php
class User extends Model
{
    use \Staudenmeir\EloquentHasManyDeep\HasRelationships;

    public function permissions()
    {
        return $this->hasManyDeep('App\Permission', ['role_user', 'App\Role', 'permission_role']);
    }
}
```

what should the foreignKeys and localKeys is? and can someone explain why it is?

**Comment by staudenmeir** [comment]
Are you using Laravel's naming convention for your tables? If so, you don't need to provide foreign or local keys.

**Comment by hugsycms** [comment]
@staudenmeir No, columns is named by myself, I want to know more about the function, can you help me ? or can you complete the docs to explain what is foreignKeys and localKeys ? thank you!

**Comment by hugsycms** [comment]
Finally, I find out the relations and guess what the foreignKeys and localKeys is, but the understanding is not thorough enough.
```php
public function permissions()
    {
        return $this->hasManyDeep(
            'App\Modules\Base\Model\AdminPermission',
            ['admin_user_roles', 'App\Modules\Base\Model\AdminRole', 'admin_role_permissions'],
            [
                'user_id', // Foreign key on the "admin_user_roles" table.
                'id',      // Foreign key on the "admin_roles" table (local key).
                'role_id', // Foreign key on the "admin_role_permissions" table.
                'id',      // Foreign key on the "admin_permissions" table.
            ],
            [
                'id',      // Local key on the "admin_users" table.
                'role_id', // Local key on the "admin_user_roles" table (foreign key).
                'id',      // Local key on the "admin_roles" table.
                'permission_id'       // Local key on the "admin_role_permissions" table.
            ]
        );
    }
```
