### ISSUE TITLE
Apply condition to intermediate model?

### ISSUE THREAD

**Issue by DanielMalmgren** [staudenmeir/eloquent-has-many-deep#118]
Hi.
Thanks for this wonderful addition to Laravel. In fact I think it's something that should be there in the core framework from the beginning. Is there any ongoing discussion about trying to get it in there?

Now to my question: Let's say I have a country which has users and users has posts. Now I need to get all posts for the country (ie a simple hasManyDeep()), but I only want to get posts by active users. Ie I want to apply a where('active', true) to the intermediate users table. Is that possible?

**Comment by staudenmeir** [comment]
Do you mean `->posts()->where('users.active', true)->get()`?

**Comment by DanielMalmgren** [comment]
Oh, do you mean that it's already doable, as easy as that? In that case I think it's not really clear from the documentation :-)

**Comment by peterthomson** [comment]
The ability to limit the intermediate model on a hasManyDeep is important and not-well documented. It's still not 100% clear from the discussion above whether a simple ->where() clause on the resulting relationship will reliably limit the results. I've been testing it and so far it seems to work, would love to see other people's results with applying conditions to the intermediate model.
