### ISSUE TITLE
More levels of Many-to-many

### ISSUE THREAD

**Issue by parelius** [staudenmeir/eloquent-has-many-deep#12]
Your extension looks very promising. However I'm not sure how it handles more levels of many-to-many relations.

Example: `App\User` belongsToMany `App\Group` belongsToMany `App\Album` belongsToMany `App\Photo`.

How would I get photos belonging to a user? I'm wondering how I would use the `hasManyDeep()` method.

**Comment by staudenmeir** [comment]
It's possible like this:

```php
class User extends Model
{
    use \Staudenmeir\EloquentHasManyDeep\HasRelationships;

    public function photos()
    {
        return $this->hasManyDeep(
            'App\Photo',
            ['group_user', 'App\Group', 'album_group', 'App\Album', 'album_photo']
        );
    }
}
```

**Comment by parelius** [comment]
Works. Thank you very much!
