### ISSUE TITLE
Question: One-To-Many to Many-To-One

### ISSUE THREAD

**Issue by regnerisch** [staudenmeir/eloquent-has-many-deep#121]
I have a table structure like that: 

```
conferences
- id

sessions
- id
- conference_id
- speaker_id

speaker
- id
```
Is it possible to use this library to create a `speakers`relation on the conference model? I do not see a hint in the documentation. 

If it is possible, how can i implement something like that? 

Thank you in advance!

**Comment by staudenmeir** [comment]
Do you mean a native `BelongsToMany` relationship?

**Comment by regnerisch** [comment]
LOL, I did not see it, you are right, it is just a BelongsToMany, I'm sorry.
