### ISSUE TITLE
Many to Many Polymorphic with morphMany

### ISSUE THREAD

**Issue by gweinxx** [staudenmeir/eloquent-has-many-deep#122]
Hi, thanks for creating this package, it really powerful, and I like it

But I have an issue where I cannot find the solution yet

I have 4 models

Post, Media, Tag and View

Post `morphMany` View
Post `belongsToMany` Tag

Media `morphMany` View

In Tag model, I want to get views from Post and Media that attached with selected Tag

`Tag.php`

`public function views() {
return $this->hasManyThrough(
'App\View',
['App\Post', 'App\Media'],
...
);
}`

Any idea how to achieve this relationship?

Thanks in advance

**Comment by staudenmeir** [comment]
Please share the migrations of all tables involved.

**Comment by gweinxx** [comment]
@staudenmeir hi, this is my table schema

`Post.php`

`Schema::create('posts', function (Blueprint $table) {`
`$table->id();`
`$table->morphs('postable');`
`$table->longText('body');`
`$table->timestampsTz();`
`$table->softDeletesTz();`
`});`

===================

`Tag.php`

`Schema::create('tags', function (Blueprint $table) {`
`$table->id();`
`$table->string('name');`
`});`

===================

`Taggable (many to many polymorphic)` 

`Schema::create('taggables', function (Blueprint $table) {`
`$table->id();`
`$table->morphs('taggable');`
`});`

===================

`Media.php`

`Schema::create('media', function (Blueprint $table) {`
`$table->id();`
`$table->morphs('mediable');`
`$table->unsignedBigInteger('post_id');`
`$table->string('type');`
`$table->string('url');`
`$table->longText('body')->nullable();`
`$table->timestampsTz();`
`$table->softDeletesTz();`
`})`

===================

`View.php`

`Schema::create('views', function (Blueprint $table) {`
`$table->id();`
`$table->unsignedBigInteger('user_id');`
`$table->morphs('viewable');`
`});`

===================

Relationship:
Post `hasMany` Media (images / videos)
Post `morphToMany` Tag
Post `morphMany` View
Media `morphToMany` Tag
Media `morphMany` View

So from `Tag.php`, I want to get all `View`  from `Post` and `Media` that attached to selected `Tag`, example:

`Tag.php`

`use \staudenmeir\.....;`

`public function views() {`
`return $this->hasManyDeep(`
`'App\View'`,
`['App\Post', 'App\View'],`
...
`);`
`};`

Is this possible?

Thanks in advance

**Comment by staudenmeir** [comment]
This relationship is possible, but requires a different package: https://github.com/staudenmeir/laravel-merged-relations
