### ISSUE TITLE
Call to undefined method App\Models\Project::hasManyDeep()

### ISSUE THREAD

**Issue by shahrukh131** [staudenmeir/eloquent-has-many-deep#124]
**project->(hasmany)users->(hasmany)tasks->(hasmany)minitasks**
![image](https://user-images.githubusercontent.com/31450736/116201185-0bfe2680-a75b-11eb-8de6-19b72a4c087c.png)
![image](https://user-images.githubusercontent.com/31450736/116201236-1a4c4280-a75b-11eb-9945-301f019ae564.png)
![image](https://user-images.githubusercontent.com/31450736/116201265-23d5aa80-a75b-11eb-865a-6e5cadefaa93.png)
![image](https://user-images.githubusercontent.com/31450736/116201336-34862080-a75b-11eb-993a-4984e6af265f.png)
**How Can I Solve This Issue?**

**Comment by sammycorgi** [comment]
You need to tell the `Project` class to use the `HasRelationships` trait.

```
use \Staudenmeir\EloquentHasManyDeep\HasRelationships;

class Project extends Model {
    use HasFactory, HasRelationships;

    ...
}
```

See more here https://www.php.net/manual/en/language.oop5.traits.php

**Comment by shahrukh131** [comment]
@sammycorgi Thank you so much 😃
