### ISSUE TITLE
Using Laravel v7  Nova - cannot get this to work

### ISSUE THREAD

**Issue by elizdlt202** [staudenmeir/eloquent-has-many-deep#127]
I followed the doc for the model. But Not sure how to call it on the resource...
Please help

**Comment by elizdlt202** [comment]
![Screen Shot 2021-06-03 at 2 34 41 PM](https://user-images.githubusercontent.com/49735067/120715038-e3173280-c478-11eb-8157-b355c9371785.png)

**Comment by staudenmeir** [comment]
I have no experience with Nova. Does the relationship itself work with something like `AccountManager::find($id)->leadtasks`?

**Comment by ahinkle** [comment]
Nova doesn’t support this. It already has a very limited support level on polymorphic and has many through relations.

This is a nova issue and not a package issue. I would recommend creating some sort of field package for nova support.

**Comment by staudenmeir** [comment]
Thanks @ahinkle!

**Comment by dan-lutd** [comment]
@ahinkle! I am coming at this from Nova as well. 
I was wondering what is preventing it from running with nova?
What error were you getting?

I am running a simple hasManyDeep on  `App\Models\User` and get the error `Call to undefined method App\Models\User::hasManyDeep`

I did add: `use \Staudenmeir\EloquentHasManyDeep\HasRelationships;`
Is something preventing the package from being found?
