### ISSUE TITLE
hasMany -> BelongsToMany-> hasMany Relation

### ISSUE THREAD

**Issue by jvbalcita** [staudenmeir/eloquent-has-many-deep#129]
Hi,

I can't find my case from the documentation or maybe I just don't know how to do it. Hope you can help me. 

Here is my relationships :
``Residential Area`` → has many → ``Brgy Proper`` → belongsToMany → ``Head Members`` → has many → ``Members``
And I want to get all the count of the members

Here's what I've tried so far and I can't make it work :(
```
class ResidentialArea extends Model
{

    public function population()
    {
        return $this->hasManyDeep(ResBrgyProper::class, [ResHeadMember::class, ResMember::class]);
    }
```

Thank you in advance! :)

**Comment by Narthall** [comment]
Hello jvbalcita,

I think the proper code line would be :

```php
class ResidentialArea extends Model
{

    public function population()
    {
        return $this->hasManyDeep(ResMember::class, [ResBrgyProper::class, ResHeadMember::class]);
    }
}
```

If I understood well, the logic behind it is:
```php
        return $this->hasManyDeep(TheDataYouReallyWant::class, [TheFirstRelationshipToGetToIt::class, TheSecondRelationshipToGetToIt::class, ..., TheLastRelationshipToGetToIt::class]);
```

**Comment by jvbalcita** [comment]
Hi @Narthall ,

I've tried the following code: 
```
class ResidentialArea extends Model
{

    public function population()
    {
        return $this->hasManyDeep(ResMember::class, [ResBrgyProper::class, ResHeadMember::class]);
    }
}
```

But it's giving me an error:

```
"message": "SQLSTATE[42S22]: Column not found: 1054 Unknown column 'res_head_members.res_brgy_proper_id' in 'on clause' (SQL: select `res_members`.*, `res_brgy_propers`.`residential_area_id` as `laravel_through_key` from `res_members` inner join `res_head_members` on `res_head_members`.`id` = `res_members`.`res_head_member_id` inner join `res_brgy_propers` on `res_brgy_propers`.`id` = `res_head_members`.`res_brgy_proper_id` where `res_head_members`.`deleted_at` is null and `res_brgy_propers`.`residential_area_id` in (1) and `res_members`.`deleted_at` is null)",
```

**Comment by jvbalcita** [comment]
> Hi @Narthall ,
> 
> I've tried the following code:
> 
> ```
> class ResidentialArea extends Model
> {
> 
>     public function population()
>     {
>         return $this->hasManyDeep(ResMember::class, [ResBrgyProper::class, ResHeadMember::class]);
>     }
> }
> ```
> 
> But it's giving me an error:
> 
> ```
> "message": "SQLSTATE[42S22]: Column not found: 1054 Unknown column 'res_head_members.res_brgy_proper_id' in 'on clause' (SQL: select `res_members`.*, `res_brgy_propers`.`residential_area_id` as `laravel_through_key` from `res_members` inner join `res_head_members` on `res_head_members`.`id` = `res_members`.`res_head_member_id` inner join `res_brgy_propers` on `res_brgy_propers`.`id` = `res_head_members`.`res_brgy_proper_id` where `res_head_members`.`deleted_at` is null and `res_brgy_propers`.`residential_area_id` in (1) and `res_members`.`deleted_at` is null)",
> ```

The ResBrgyProper has the ID of Residential Area, while the ResHeadMembers is belongsToMany using this table ``residence_brgy_proper_has_residents`` that has the id of ResBrgyProper and ResHeadMember then the ResMember has the ID of ResHeadMember

**Comment by staudenmeir** [comment]
You are missing the pivot table:

```php
class ResidentialArea extends Model
{

    public function population()
    {
        return $this->hasManyDeep(
            ResMember::class,
            [ResBrgyProper::class, 'residence_brgy_proper_has_residents ', ResHeadMember::class]
        );
    }
}
```

@Narthall Thanks for your help.

**Comment by jvbalcita** [comment]
Yes @staudenmeir, I figure that out too just moment ago. I never thought it would work. Thank you for this @staudenmeir :) It's working like a charm 👍
