### ISSUE TITLE
[Help] Can not make the relation hasMany -> MorphToMany

### ISSUE THREAD

**Issue by MehdiAghighi** [staudenmeir/eloquent-has-many-deep#133]
hello.
i have a situation that in any way i can't build the relation that is needed. can anyone please help?

my situation is like this. i have a courses table and a topics table. 
the topics table has a course_id filed that makes a belongsTo relation to courses.
also i have a videos table that the course videos are in it. but it doesn't have a course id or a topic_id because it has a many To Many polyphormic relationship topics. that mean there is a pivot table called topicables that has topic_id and topicable_type and topicable_id.

i tried a lot of ways to make courses to videos relation with this package but i couldn't !
this is one of my tries:

```php
$this->hasManyDeep(
            'App\Models\Video',
            ['App\Models\Topic', 'topicables'],
            ['course_id', ['topicable_type', 'topicable_id'], 'id'],
            [null, null, 'topicable_id']
        )
```
```sql
"select * from `videos` inner join `topicables` on `topicables`.`topicable_id` = `videos`.`id` inner join `topics` on `topics`.`id` = `topicables`.`topicable_id` where `topicables`.`topicable_type` = ? and `topics`.`course_id` = ?"
```
it generates the query above but it doesn't make sense ( `topics` on `topics`.`id` = `topicables`.`topicable_id` ) this part speccialy

**Comment by staudenmeir** [comment]
In the direction you are looking for, the second part is a `MorphedByMany` relationship instead of `MorphToMany`:

```php
class Course extends Model
{
    use \Staudenmeir\EloquentHasManyDeep\HasRelationships;

    public function videos() {
        return $this->hasManyDeep(
            'App\Models\Video',
            ['App\Models\Topic', 'topicables'],
            [null, 'topic_id', 'id'],
            [null, null, ['topicable_type', 'topicable_id']]
        );
    }
}
```

**Comment by MehdiAghighi** [comment]
Thank you so much that worked :)
are there any blog posts or something that you wrote that explains these packages a little bit more ? i think it is a little hard to understand from readme files.

**Comment by MehdiAghighi** [comment]
can you please also provide Video -> Course relation in exmaple above ? i really can't find a workaround for these

**Comment by staudenmeir** [comment]
No, there aren't any. For complex cases like this it's often easiest to concatenate existing relationships:
https://github.com/staudenmeir/eloquent-has-many-deep#existing-relationships
