### ISSUE TITLE
MorphedByMany and BelongsTo

### ISSUE THREAD

**Issue by juliuscaesarnl** [staudenmeir/eloquent-has-many-deep#14]
Hi,

First of all, thank you for creating this extension. It's very useful and I think it should be added to Laravel.

My question: is it possible to combine MorphedByMany with BelongsTo?
Example: <code>User</code> -> morphedByMany -> <code>Account</code> -> belongsTo -> <code>Partner</code>

Currently I'm using this line to retrieve <code>Partner</code> models:
<code>$user->accounts()->with('partner')->withTrashed()->get()->pluck('partner')->unique()</code>

I'm hoping there is a better way to do this.

Thank you in advance!

**Comment by juliuscaesarnl** [comment]
Glad to hear that!
In my User model:
```php
    public function accounts()
    {
        return $this->morphedByMany(Account::class, 'userable');
    }
```

**Comment by staudenmeir** [comment]
Use this:

```php
class User extends Model
{
    use \Staudenmeir\EloquentHasManyDeep\HasRelationships;

    public function partners()
    {
        return $this->hasManyDeep(
            Partner::class,
            ['userables', Account::class],
            [null, 'id', 'id'],
            [null, ['userable_type', 'userable_id'], 'partner_id']
        );
    }
}
```

**Comment by juliuscaesarnl** [comment]
Wow thanks a lot, you're a lifesaver!

**Comment by staudenmeir** [comment]
I added a new feature that allows you to define a `HasManyDeep` relationship using existing relationships:
https://github.com/staudenmeir/eloquent-has-many-deep#existing-relationships

You could use it like this:

```php
class User extends Model
{
    use \Staudenmeir\EloquentHasManyDeep\HasRelationships;

    public function partners()
    {
        return $this->hasManyDeepFromRelations($this->accounts(), (new Account)->partner());
    }
}
```

**Comment by juliuscaesarnl** [comment]
Thank you for this function, it's a great addition. However, my Account model uses the SoftDeletes trait and I can't seem to include soft deleted models like this:
```php
    public function partnersThroughAccounts()
    {
        return $this->hasManyDeepFromRelations($this->accounts()->withTrashed(), (new Account())->partner());
    }
```

**Comment by staudenmeir** [comment]
Unfortunately, this is not possible at the moment. It's a limitation of the underlying `HasManyThrough` relationship (https://github.com/laravel/framework/issues/23039, https://github.com/laravel/ideas/issues/1070) that is still unsolved.

**Comment by juliuscaesarnl** [comment]
I see, that is unfortunate. I'll keep an eye on that in the meantime. Thanks for your help.

**Comment by staudenmeir** [comment]
I added support for `withTrashed()` on intermediate models in the latest release:
https://github.com/staudenmeir/eloquent-has-many-deep#soft-deleting

Use it like this:

```php
public function partnersThroughAccounts()
{
    return $this->hasManyDeepFromRelations($this->accounts(), (new Account())->partner())
        ->withTrashed('accounts.deleted_at');
}
```

**Comment by juliuscaesarnl** [comment]
Works like a charm! I really appreciate your effort.
