### ISSUE TITLE
Support for Laravel 6 with PHP 8

### ISSUE THREAD

**Issue by janalwin** [staudenmeir/eloquent-has-many-deep#143]
Hallo,

We are upgrading our Laravel 6 application to PHP 8.  Unfortunately, the Laravel 6 compatible release 1.11 of Eloquent-has-many-deep, doesn't support PHP 8. 

I've made a small fix in the composer.json file to get it working:
https://github.com/dit-werkt/eloquent-has-many-deep/commit/6e24c0277f794e55319c62b5f0bf4ae22d6e15d2

Could you integrate this change in an official release?

I've run the unit tests and I get no failures.

I can't make a Pull Request because their is no 1.11 branch in your repo. There is only a v1.11 tag.

Best regards,

Jan Alwin de Jong

**Comment by staudenmeir** [comment]
Absolutely, I'll take of care it.
