### ISSUE TITLE
Self referencing has many deep

### ISSUE THREAD

**Issue by mokhosh** [staudenmeir/eloquent-has-many-deep#148]
I'm creating an app where you can have connected ideas, so ideas would have many ideas, but if I create an `idea_idea` table I would have `idea_one_id` and `idea_two_id` which is a one way relationship.
So, I've created another model called a `Connection` which only has an `id`. Then I have `connection_idea` table that I can use to relate many ideas to a single connection.

Now I need to be able to get connected ideas of an idea. `Idea --belongsToMany--> Connection --belongsToMany--> Idea`
but when I use this code:
```php
    public function relatedIdeas()
    {
        return $this->hasManyDeepFromRelations(
            $this->connections(),
            (new Connection)->ideas(),
        );
    }
```

I get this error: 
```
Syntax error or access violation: 1066 Not unique table/alias: 'connection_idea'
```

and when I use this method:
```php
    public function relatedIdeas()
    {
        return $this->hasManyDeep(
            Idea::class,
            ['connection_idea', Idea::class],
        );
    }
```
i get this:
```
Syntax error or access violation: 1066 Not unique table/alias: 'ideas'
```

**Comment by staudenmeir** [comment]
This special case requires a custom model for the pivot table to set the alias:

```php
class Idea extends Model
{
    use HasRelationships;

    public function relatedIdeas()
    {
        return $this->hasManyDeep(
            Idea::class,
            [ConnectionIdea::class, Connection::class, ConnectionIdea::class . ' as alias'],
        );
    }
}
```

```php
use Illuminate\Database\Eloquent\Relations\Pivot;
use Staudenmeir\EloquentHasManyDeep\HasTableAlias;

class ConnectionIdea extends Pivot
{
    use HasTableAlias;
}
```

**Comment by mokhosh** [comment]
Thanks, I used this and it returns the idea from which you're calling the relationship itself as a related idea. I added `->where('alias.idea_id', '!=', $this->id)`, hopefully it won't create unexpected behaviour in the future?

**Comment by staudenmeir** [comment]
You can't/shouldn't use `$this` in Laravel relationships because it breaks eager loading. Use this instead:

```php
class Idea extends Model
{
    use HasRelationships;

    public function relatedIdeas()
    {
        return $this->hasManyDeep(
            Idea::class,
            [ConnectionIdea::class, Connection::class, ConnectionIdea::class . ' as alias'],
        )->whereColumn('alias.idea_id', '!=', 'connection_idea.idea_id');
    }
}
```

**Comment by mokhosh** [comment]
Thanks, great tip.
