### ISSUE TITLE
Incorrect join if alias is used

### ISSUE THREAD

**Issue by nerg4l** [staudenmeir/eloquent-has-many-deep#15]
Hi!

If I have something like the following:

```php
class Post extends Model
{
    public function similar()
    {
        return $this->hasManyDeep(
            self::class,
            ['taggable as alias', Tag::class, 'taggable']
        );
    }
}
```

The following sql is generated:

```sql
select "posts".*, "taggable" as "alias.post_post_pk"
from "posts"
       inner join "taggable" on "taggable"."post_post_pk" = "posts"."post_pk"
       inner join "tags" on "tags"."tag_pk" = "taggable"."tag_tag_pk"
       inner join "taggable" as "alias" on "taggable" as "alias.tag_tag_pk" = "tags"."tag_pk"
where "taggable" as "alias.post_post_pk" = 1
```

As you can see the `"taggable" as "alias.tag_tag_pk"` is the problematic part.

The error first occurs in [`HasManyDeep:110`](https://github.com/staudenmeir/eloquent-has-many-deep/blob/master/src/HasManyDeep.php#L110) as inside `Model::qualifyColumn` `$this->getTable()` returns `project_category as alias`. Then `$this->getQualifiedFirstKeyName()` returns the same so when the where is added this generates the wrong alias.

*Edit:* Example is replaced with Models from the test of this package.

**Comment by staudenmeir** [comment]
As the documentation mentions, you have to use the `HasTableAlias` trait in the model you are aliasing.

In this case, it's a bit more complicated. Create a pivot model for the `taggable` table:

```php
class Taggable extends \Illuminate\Database\Eloquent\Relations\Pivot
{
    use \Staudenmeir\EloquentHasManyDeep\HasTableAlias;

    protected $table = 'taggable';
}
```

Then use it like this:

```php
class Post extends Model
{
    public function similar()
    {
        return $this->hasManyDeep(
            self::class,
            [Taggable::class.' as alias', Tag::class, 'taggable']
        );
    }
}
```

**Comment by nerg4l** [comment]
Oh, so sorry I missed that.
