### ISSUE TITLE
Support custom relations

### ISSUE THREAD

**Issue by G3z** [staudenmeir/eloquent-has-many-deep#152]
sometimes Laravel relations are not enough and custom classes can be created to define custom relations, for example https://github.com/lazychaser/laravel-nestedset
it's not possible to use this kind of relations with this package.
Is it possible to develop a contract to be implemented on those relations to enable deep relationing ?

**Comment by staudenmeir** [comment]
It's basically impossible to develop a contract like that. I looked into supporting other complex relationships from my packages https://github.com/staudenmeir/laravel-adjacency-list and https://github.com/staudenmeir/eloquent-json-relations and it would have required _a lot_ of work.

It's not only complicated to generate the SQL for fetching deep relationships like that, but they (can) have highly customized "post-processing" of query results – especially for eager loading.

Do you have a specific use case for https://github.com/lazychaser/laravel-nestedset?

**Comment by G3z** [comment]
Thank you fro your response.

I use it to model a hierarchical user group structure
groups
```parent group
-child group
-granchild group
-child group
```
then I have things associated  (`clients`, `permissions`, etc..) to `parent group` or `granchild group` and `users` associated to `parent group` are associated also to `clients` in a hierarchical way: `clients` set on `granchild` are associated to `users` in `parent group`
Then I can have other things associated to `clients`, like `machines` and I should be able to tell that a user  has many machines through `user`->`groups`->`clients`->`machines`

As of now I have created a service class to get `User->Client` and  `User->Machine` relation

**Comment by staudenmeir** [comment]
> As of now I have created a service class to get User->Client and User->Machine relation

Can you share this class?

**Comment by G3z** [comment]
I've set up a [PHPSanddbox](https://phpsandbox.io/e/x/lrasx?layout=EditorPreview&defaultPath=%2F&theme=dark&showExplorer=no&openedFiles= )


I would like a deep relation from User to Machine,
please have a look at `DatabaseSeeder.php` and `welcome.blade.php`

**Comment by staudenmeir** [comment]
Thanks, I'll take a look.

**Comment by staudenmeir** [comment]
Do you want to use other nested set relationships besides `descendants` in deep relationships?

**Comment by G3z** [comment]
Ideally I would like to support [all](https://github.com/lazychaser/laravel-nestedset#retrieving-nodes) relations, if you show me how to support a "custom" relation I'll send a PR for the others.

**Comment by staudenmeir** [comment]
I pushed a draft to the `descendants` branch. Update the package to `dev-descendants` to test it in your project.

You need to adjust your models because the deep relationship requires an [alias](https://github.com/staudenmeir/eloquent-has-many-deep#table-aliases) for `Hierarchy` as it occurs twice in the path. Unfortunately, the `descendants` relationship isn't initialized correctly and you need to override it:

```php
class User extends Model
{
    public function extended_hierarchies()
    {
        return $this->hasManyDeepFromRelations($this->hierarchies(), (new Hierarchy)->setAlias('alias')->descendants());
    }
}
```

```php
use Kalnoy\Nestedset\DescendantsRelation;
use Staudenmeir\EloquentHasManyDeep\HasTableAlias;

class Hierarchy extends Model
{
    use HasTableAlias;

    public function descendants()
    {
        return new DescendantsRelation((new $this)->newQuery(), $this);
    }
}
```

If this works for you, we'll have to see how similar the other relationships are.

**Comment by G3z** [comment]
It's perfect!
I've updated the [phpsandbox]( https://phpsandbox.io/e/x/lrasx?layout=EditorPreview&defaultPath=%2F&theme=dark&showExplorer=yes&openedFiles= )
(I've also installed debugbar)
and everything works like a charm

**Comment by G3z** [comment]
I've noticed a bug:
if you try `dd($user->extended_hierarchies;)` this error is returned
```
SQLSTATE[HY000]: General error: 1 ambiguous column name: hu._lft (SQL: select "hierarchies" as "hu.*", "hierarchy_user"."user_id" as "laravel_through_key" from "hierarchies" as "hu" inner join "hierarchies" as "hu" on "hu"."_lft" between "hu"."_lft" + 1 and "hu"."_rgt" inner join "hierarchy_user" on "hierarchy_user"."hierarchy_id" = "hu"."id" where "hierarchy_user"."user_id" = 1)
```

**Comment by staudenmeir** [comment]
How is your `extended_hierarchies` relationship defined?

**Comment by G3z** [comment]
it's the one you posted https://github.com/staudenmeir/eloquent-has-many-deep/issues/152#issuecomment-1035534848

**Comment by staudenmeir** [comment]
> It's perfect!

Which query worked?

> if you try dd($user->extended_hierarchies;) this error is returned

`$user->extended_hierarchies` works for me.

> How is your extended_hierarchies relationship defined?

I asked because you changed the alias and maybe changed something else.

**Comment by G3z** [comment]
I'm very sorry, you are correct. 
I did remove this because `$user->machines` was working without it  but now i understand why it's important
```php
public function descendants()
    {
        return new DescendantsRelation((new $this)->newQuery(), $this);
    }
```
as you made it everything works, sorry again 🙇🏼‍♂️

**Comment by GreenImp** [comment]
@staudenmeir this looks good, is there any chance of getting it working with ascendants as well?

I have a Model, which has a `node` relationship. `node` is a nested set leaf.
On my model, I then want another relationship for the top level parent of the `node`.

Using nested sets, I can do something like:

```php
$model->node->ancestors()->whereIsRoot()->first();
```

As a relationship, the query needs to look something like (Where `?` is the ID of the model's `node`):

```mysql
select *
from brands
         join brands as through
              on through._rgt between brands._lft and brands._rgt
where brands.id != ?
      and brands.parent_id is null;
```

**Comment by staudenmeir** [comment]
@G3z Did you find some time to look at any of the other nested set relationships?

**Comment by staudenmeir** [comment]
@GreenImp What Laravel version are you using?
