### ISSUE TITLE
whereHas on through table

### ISSUE THREAD

**Issue by sbc640964** [staudenmeir/eloquent-has-many-deep#157]
@staudenmeir  Greetings
Is it possible to use whereHas on the intermediate table

for example:
I would like to get from the meta_records table certain lines provided the record has other lines that answer my query.

In my plot I want to get the meta of the records associated with the current record by their meta

so:
```php
class Record {
  public function hasManyRecordsData() : HasManyDeep
  {
      return $this->hasManyDeep(
          RecordMeta::class,
          [RecordMeta::class . ' as data1', Record::class . ' as records1'],
          ['value', 'id', 'record_id'],
          ['id', 'record_id', 'id']
      );
  }

  public function data(): HasMany
  {
      return $this->hasMany(RecordMeta::class);
  }
}


Record::with(['hasManyRecordsData' => fn($query)
    $query->where('records1.collection_id', $collection)
    ->where('data1.field_id', $meta_field_id)
);])

```

Now all I want is to query record1 whereHas meta with a certain key and value

**Comment by staudenmeir** [comment]
> Record::with(['hasManyRecordsData' => fn($query)
    $query->where('records1.collection_id', $collection)
    ->where('data1.field_id', $meta_field_id)
);])


Did you run this query (with valid PHP syntax)? If so, what result are getting compared to the expected result?
