### ISSUE TITLE
HasManyThroughBelongsToMany

### ISSUE THREAD

**Issue by sasureshkumar** [staudenmeir/eloquent-has-many-deep#16]
<img width="659" alt="screen shot 2019-01-01 at 3 41 26 pm" src="https://user-images.githubusercontent.com/493515/50571932-c4aa3a00-0ddb-11e9-9370-c716d74accc4.png">

```php
class BroadActivity extends Model
{
    use HasRelationships;
    public function detailActivities()
    {
        return $this->hasMany(DetailActivity::class);
    }
    public function targets()
    {
        // How to relate the Targets with pivot value (target_value)?
    }
}
```

```php
class DetailActivity extends Model
{
    public function broadActivity()
    {
        return $this->belongsTo(BroadActivity::class);
    }
    public function targets()
    {
        return $this->belongsToMany(Target::class)->withPivot('target_value');
    }
}
```

```php
class Target extends Model
{
    public function detailActivities()
    {
        return $this->belongsToMany(DetailActivity::class);
    }
}
```

How to create a relation in BroadActivity model to Target with additional pivot values?

**Comment by staudenmeir** [comment]
Use this:

```php
class BroadActivity extends Model
{
    use HasRelationships;

    public function targets()
    {
        return $this->hasManyDeep(
            Target::class, [DetailActivity::class, 'detail_activity_target']
        )->withPivot('detail_activity_target', ['target_value']);
    }
}
```

**Comment by sasureshkumar** [comment]
@staudenmeir really appreciating your response within a short time (maybe holiday there) and it works perfectly.

I have one more question, actually not related to your package, but it may help others like me.

If I want to sum the 'target_value' and group by the target, how can I do that?

<img width="762" alt="screen shot 2019-01-01 at 3 36 13 pm" src="https://user-images.githubusercontent.com/493515/50571901-025a9300-0ddb-11e9-8d63-10fd104c5746.png">

**Comment by staudenmeir** [comment]
Try this for a single `$broadActivity`:

```php
$broadActivity->targets()
    ->select('targets.name', DB::raw('sum(target_value) target_value'))
    ->groupBy('targets.name')
    ->getQuery()
    ->get();
```

Or do you want to query multiple `BroadActivity`s at once?

**Comment by sasureshkumar** [comment]
Thanks, @staudenmeir from my current requirement, I only need for a single BA. It works.
