### ISSUE TITLE
deleted_at conflict

### ISSUE THREAD

**Issue by invaders-xx** [staudenmeir/eloquent-has-many-deep#160]
I have 3 tables 
"Product" morphMany "Inventory" hasMany "Stock"

So in product I created a relationship

$this->hasManyDeepFromRelations($this->inventories(), (new Inventory)->stocks());

where product has a MorphMany relation called inventories and Inventory has a hasMany relation called stocks

But I have this issue: SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'deleted_at' in where clause is ambiguous

select count(*) as aggregate from `inventory_stocks` inner join `inventory_inventories` on `inventory_inventories`.`id` = `inventory_stocks`.`inventory_id` where `inventory_inventories`.`entity_id` = 2 and `inventory_inventories`.`entity_type` = Modules\Traceability\Entities\Company\Product\Product and (`deleted_at` is null) and `inventory_stocks`.`deleted_at` is null and `inventory_inventories`.`deleted_at` is null

Any idea how to fix that ?

Many thanks in advance.

**Comment by staudenmeir** [comment]
How are you using the `HasManyDeep` relationship in your query? How are `inventories()` and `stocks()` defined?

**Comment by invaders-xx** [comment]
/**
     * The MorphOne inventories relationship.
     *
     * @return MorphMany
     */
    public function inventories(): MorphMany
    {
        return $this->MorphMany(Inventory::class, 'entity');
    }

/**
     * The hasMany stocks relationship.
     *
     * @return HasMany
     */
    public function stocks(): HasMany
    {
        return $this->hasMany(InventoryStock::class, 'inventory_id', 'id');
    }

**Comment by staudenmeir** [comment]
How are you using the `HasManyDeep` relationship in your code? What query are you executing to get this error?

**Comment by invaders-xx** [comment]
$record->stocks()->withTrashed()->getQuery();

**Comment by invaders-xx** [comment]
maybe I should use another syntax for the HasManyDeep relation

**Comment by invaders-xx** [comment]
Forget my bad. Thanks for your help.
