### ISSUE TITLE
How to get User Favorites:

### ISSUE THREAD

**Issue by Aliakbari1994** [staudenmeir/eloquent-has-many-deep#173]
Hello, How to get User Favorites:

[User] --> HasMany --> [Favorite] --> MorphTo --> [Post, Video, Image]

Favorite Table: user_id, favoritable_type, favoritable_id

I need a relation to get user favorite posts in user model.

**Comment by staudenmeir** [comment]
Hi @Aliakbari1994,

Use this relationship:

```php
class User extends Model
{
    use \Staudenmeir\EloquentHasManyDeep\HasRelationships;

    public function favoritePosts()
    {
        return $this->hasManyDeep(
            Post::class,
            [Favorite::class, 'favoritables'],
            [null, null, 'id'],
            [null, null, ['favoritable_type', 'favoritable_id']]
        );
    }
}
```

**Comment by Aliakbari1994** [comment]
Hi @staudenmeir thanks;
im get this error:
"message": "SQLSTATE[42000]: Syntax error or access violation: 1066 Not unique table/alias: 'favoritables' (SQL: select count(*) as aggregate from `posts` inner join `favoritables` on `favoritables`.`favoritable_id` = `posts`.`id` inner join `favoritables` on `favoritables`.`id` = `favoritables`.`favoritable_id` where `favorites`.`favoritable_type` = App\\Post and `favorites`.`user_id` = 8 and `posts`.`deleted_at` is null)",

**Comment by Aliakbari1994** [comment]
this is ok:
class User extends Model
{
    use \Staudenmeir\EloquentHasManyDeep\HasRelationships;

    public function favoritePosts()
    {
        return $this->hasManyDeep(
            Post::class,
            [Favorite::class],
            [null, null, 'id'],
            [null, null, ['favoritable_type', 'favoritable_id']]
        );
    }
}

**Comment by staudenmeir** [comment]
Ah, I thought there's an additional level. Is your issue solved?

**Comment by Aliakbari1994** [comment]
Yes, my problem is solved. The question is, how can I sort the received records based on the favoritables table?

**Comment by staudenmeir** [comment]
Yes, that's correct.
