### ISSUE TITLE
php version is not compatible 

### ISSUE THREAD

**Issue by MakhmudovMurod** [staudenmeir/eloquent-has-many-deep#176]
Problem 1
    - Root composer.json requires staudenmeir/eloquent-has-many-deep 1.13 -> satisfiable by staudenmeir/eloquent-has-many-deep[v1.13].
    - staudenmeir/eloquent-has-many-deep v1.13 requires php ^7.3 -> your php version (8.1.5) does not satisfy that requirement.    
How Can I fix this?

**Comment by staudenmeir** [comment]
Hi @MakhmudovMurod,
What Laravel version are you using?

**Comment by MakhmudovMurod** [comment]
Laravel 8

**Comment by MakhmudovMurod** [comment]
Problem is solved.
