### ISSUE TITLE
Push to laravel / framework?

### ISSUE THREAD

**Issue by sidewaysglance** [staudenmeir/eloquent-has-many-deep#177]
This package is so useful, thank you!

It is performant as it makes proper use of the database, and is much more versatile than standard eloquent relations.

Why not push to https://github.com/laravel/framework?

**Comment by staudenmeir** [comment]
Thanks @sidewaysglance. With all the additional functionality, the package's code and documentation have grown quite a bit over time and so I think it's better to keep it as a separate package.

**Comment by staudenmeir** [comment]
@robman70 Wrong ticket ;-)

**Comment by robman70** [comment]
Oops... sorry! I was reading this ticket and replied to this one instead of the one I opened

**Comment by decadence** [comment]
I second that (and the same request for belongs-to-through package). I think every Laravel user would be happy to have those in core.

Anyway great work @staudenmeir. Thanks for creating and maintaining these packages!
