### ISSUE TITLE
Category -> hasMany -> Post -> belongsTo -> User

### ISSUE THREAD

**Issue by jesperbjoernandersen** [staudenmeir/eloquent-has-many-deep#180]
I'm trying to get all users who has posted in the given category. The relationships are as described in the title. How would I go about accomplishing this? Tried with hasManyDeepFromRelations, but that doesn't seem to work.

**Comment by staudenmeir** [comment]
Hi @jesperbjoernandersen,

> Tried with hasManyDeepFromRelations, but that doesn't seem to work.

What code did you try? What didn't work?

**Comment by jesperbjoernandersen** [comment]
```php
class Category extends Model
{
    public function posts()
    {
        return $this->hasMany(Post::class)
    }

    public function users()
    {
        return $this->hasManyDeepFromRelations($this->posts(), (new Post())->user());
    }
}

class Post extends Model
{
    public function user()
    {
        return $this->belongsTo(User::class)
    }
}

class User extends Model
{
    public function posts()
    {
        return $this->hasMany(Post::class)
    }
}
```

**Comment by staudenmeir** [comment]
What didn't work? What query did you execute? Is there an error?

**Comment by jesperbjoernandersen** [comment]
Okay, I deleted everything and rewrote the code. Now it works. Must have had a typo or something somewhere. It just returned nothing. Like an empty collection, but now the collection is filled. My bad, sorry.

**Comment by decadence** [comment]
In this scenario will be duplicated users or only unique in relationship result? If category has multiple posts from the same user.
