### ISSUE TITLE
Compatibility with has-many-merged relashionships

### ISSUE THREAD

**Issue by Agufi28** [staudenmeir/eloquent-has-many-deep#182]
Hi, I was wondering if by any chance compatibility could be added with the following library:
https://github.com/korridor/laravel-has-many-merged

I've tried to use it as is but i get an error saying "This relashionship is not supported"

![image](https://user-images.githubusercontent.com/45501721/214919758-1bb9b995-8531-42e2-97f3-0a807744c151.png)

Thank you very much!

**Comment by staudenmeir** [comment]
How are you using that package and what does your `hasManyDeepFromRelations()` relationship look like?

**Comment by Agufi28** [comment]
Hi, thank you for your help!  
This is the main relationship (CuerpoTecnico):
![image](https://user-images.githubusercontent.com/45501721/215189855-49a69f41-b034-49a7-8f21-4e533afed9f5.png)

And this is how the relationship within the Subcategoria model:
![image](https://user-images.githubusercontent.com/45501721/215190107-d56a8121-c5dd-4219-946e-84c79011b133.png)

It fails when i try to access the relation "clasesDeHoy" from a CuerpoTecnico collection

Thanks!

**Comment by staudenmeir** [comment]
What Laravel version are you using?

**Comment by Agufi28** [comment]
I'm using laravel 9. Thanks!

**Comment by staudenmeir** [comment]
I pushed a draft into the `has-many-merged` branch. You can test it by replacing the version in your `composer.json`:

```json
"staudenmeir/eloquent-has-many-deep": "dev-has-many-merged"
```

**Comment by Agufi28** [comment]
It works great. Thank you very much!! :D

**Comment by staudenmeir** [comment]
Great, I released a new version. You can revert the `composer.json` change and update the package to `v1.17.1`.
