### ISSUE TITLE
withCount functionality

### ISSUE THREAD

**Issue by CrisGuzmanS** [staudenmeir/eloquent-has-many-deep#185]
is there a way to implement withCount functionality? this is what i am trying to do:

![image](https://user-images.githubusercontent.com/51240376/220399343-c6abd8e0-627c-4452-95b4-fceb3b0891e4.png)

My model is: Person -> PersonPublication -> Publication -> PublicationCitation -> Citation
My implementation is working fine, but i am not able to use withCount, is there a way to implement it?

**Comment by staudenmeir** [comment]
Hi @CrisGuzmanS,
The issue is not `withCount()` here but the `having()` clause. 

I explained this here and showed a workaround: https://github.com/laravel/framework/issues/30184#issuecomment-538491118

**Comment by CrisGuzmanS** [comment]
Thank you @staudenmeir that is true. For other developer that are facing the same problem than me, i found this solution: `Person::has('citations','>',$number);`
