### ISSUE TITLE
PHPStorm warns about trait collision with "ConcatenatesRelationships"

### ISSUE THREAD

**Issue by roberttolton** [staudenmeir/eloquent-has-many-deep#195]
Hi, many thanks for this package.

Recently, PHPStorm has been warning me, with models that were once previously clear of warnings, of the following:

```
Trait method 'hasOneOrManyDeepFromBelongsTo' will not be applied because it collides with 'ConcatenatesRelationships'
Trait method 'hasOneOrManyDeepFromBelongsToMany' will not be applied because it collides with 'ConcatenatesRelationships'
Trait method 'hasOneOrManyDeepFromHasManyThrough' will not be applied because it collides with 'ConcatenatesRelationships'
Trait method 'hasOneOrManyDeepFromHasOneOrMany' will not be applied because it collides with 'ConcatenatesRelationships'
Trait method 'hasOneOrManyDeepFromMorphOneOrMany' will not be applied because it collides with 'ConcatenatesRelationships'
Trait method 'hasOneOrManyDeepFromMorphToMany' will not be applied because it collides with 'ConcatenatesRelationships'
Trait method 'hasOneOrManyDeepRelationMethod' will not be applied because it collides with 'ConcatenatesRelationships'
```

My model just uses `HasRelationships`.

Is this anything to worry about?

**Comment by staudenmeir** [comment]
Can you share a screenshot of the warning(s)? Is it shown on the line `use HasRelationships;`?

**Comment by chrisworrell** [comment]
![image](https://github.com/staudenmeir/eloquent-has-many-deep/assets/1687097/d6cb6f4a-9e8e-4d80-854e-9bac60b0447a)
here you go, i just ran into this upgrading to laravel 10 and php82 @staudenmeir

**Comment by staudenmeir** [comment]
Really weird These methods exist in the `ConcatenatesRelationships` trait so the warnings don't make sense. Looks like an issue with the PhpStorm cache.

**Comment by roberttolton** [comment]
@chrisworrell Thanks for the screenshot - that's what I'm seeing as well.

![Screenshot 2023-05-16 at 22 41 57](https://github.com/staudenmeir/eloquent-has-many-deep/assets/3510875/561353aa-35b7-4a22-9a84-b73c33cd4d93)

**Comment by chrisworrell** [comment]
I tried clearing the full cache in phpstorm but i am still getting the error, strange because another person i know that uses the same version and php 8.1 is not getting it 🤷

**Comment by chrisworrell** [comment]
yea i dont think its related to this package i just ran into the following with laravel cashier

![image](https://github.com/staudenmeir/eloquent-has-many-deep/assets/1687097/5ade7902-07b7-4520-82d1-dd174d607ccc)

**Comment by chrisworrell** [comment]
@roberttolton are you using vapor?  i noticed my local system had a new .vapor that essentially duplicated the entire package structure of what my laravel system had, i removed that and the errors are gone, im betting you have some sort of duplication like i had and phpstorm is picking up on it

**Comment by staudenmeir** [comment]
https://www.paypal.com/paypalme/JonasStaudenmeir ;-) Thanks!

**Comment by roberttolton** [comment]
@chrisworrell I'm not using Vapor, and I don't have any `.vapor` folder in my project. I can't find any duplication, but I did have a custom Laravel package added to the Project window in PHPStorm, and detaching that seems to have sorted it..? So indeed, sorry for the bother @staudenmeir
