### ISSUE TITLE
places → belongs to department stores → belongs to many → promotions

### ISSUE THREAD

**Issue by lxrco-sanjit** [staudenmeir/eloquent-has-many-deep#196]
I am currently facing difficulties in creating a `promotions` relation on the `Place` model using this package. I have the following table structure:

places |
--------|
PlaceId | 
department_store_id |

department_stores | 
-|
id

department_store_promotions|
---|
department_store_id | 
promotion_id |

promotions |
--|
id |

I have tried various approaches to create the 'promotions' relation on the 'Place' model, but none have been successful so far. Any help or suggestions would be greatly appreciated.

**Comment by staudenmeir** [comment]
Hi @lxrco-sanjit,
Use this relationship:

```php
class Place extends Model
{
    use \Staudenmeir\EloquentHasManyDeep\HasRelationships;

    public function promotions()
    {
        return $this->hasManyDeep(
            Promotion::class,
            [DepartmentStore::class, 'department_store_promotions'],
            ['id'],
            ['department_store_id']
        );
    }
}
```

**Comment by lxrco-sanjit** [comment]
That works. Thank you!
