### ISSUE TITLE
Privot id column at hasManyDeep relation

### ISSUE THREAD

**Issue by hogggerty** [staudenmeir/eloquent-has-many-deep#20]
Hello, i have hasManyDeep relation using table aliases and in result i have my result model columns and one column of one pivot tables.
Like:

> select `vertices`.*, `head_vertices`.`user_id` from 

head_vertices.user_id is not a part of result model columns.

If i try to add select('vertices.*') to relation, it doesn't change anything. The only way to hide this column is use getQuery()->select('vertices.*'). But in this case i get a Builder instance instead a relationship instance.

**Comment by staudenmeir** [comment]
Please post the relationship and the query that uses it.

**Comment by hogggerty** [comment]
Relationship:
<pre>
public function tail_vertices(){
        return $this->hasManyDeep(
            Vertex::class,
            [
                Vertex::class.' as head_vertices',
                Edge::class.' as head_edges',
            ], 
            [
               'user_id',
               'head_id',
               'id',
            ],
            [
              'id',
              'id' ,
              'tail_id',
            ]
            );
}
</pre>

Result query:
<pre>SELECT
    `vertices`.*,
    `head_vertices`.`user_id`
FROM
    `vertices`
INNER JOIN `edges` AS `head_edges`
ON
    `head_edges`.`tail_id` = `vertices`.`id`
INNER JOIN `vertices` AS `head_vertices`
ON
    `head_vertices`.`id` = `head_edges`.`head_id`
WHERE
    `head_edges`.`deleted_at` IS NULL AND `head_vertices`.`deleted_at` IS NULL AND `head_vertices`.`user_id` = 1 AND `vertices`.`deleted_at` IS NULL</pre>

**Comment by staudenmeir** [comment]
The additional column is required for matching eager loading results to their parents.

Are you asking because the column overrides the value of `user_id` in the result?

Laravel 5.8 will fix this issue by aliasing the column: https://github.com/laravel/framework/pull/25812

**Comment by hogggerty** [comment]
Thanks for the quick response.
