### ISSUE TITLE
IDE helpers

### ISSUE THREAD

**Issue by nandi95** [staudenmeir/eloquent-has-many-deep#202]
Just like in the [adjacency package](https://github.com/staudenmeir/laravel-adjacency-list/pull/131) it would be great if a hook can be added to this package as currently the relations from this package are not being picked up.

**Comment by staudenmeir** [comment]
Hi @nandi95,
Good idea, I released a new version with the hook:
https://github.com/staudenmeir/eloquent-has-many-deep#ide-helper

**Comment by nandi95** [comment]
This fails for me on a getter,
I have a cost and a unit_amount column in the db and on the model I have an accessor `getUnitCostAttribute`. This does: `return $this->cost / $this->unit_amount;` 

```
Exception: Division by zero
Could not analyze class App\Models\Ingredient.

Trace:
#0 [internal function]: App\Models\Ingredient->getUnitCostAttribute()
#1 /Users/user/Web/project/vendor/staudenmeir/eloquent-has-many-deep/src/IdeHelper/DeepRelationsHook.php(35): ReflectionMethod->invoke(Object(App\Models\Ingredient))
#2 /Users/user/Web/project/vendor/barryvdh/laravel-ide-helper/src/Console/ModelsCommand.php(1587): Staudenmeir\EloquentHasManyDeep\IdeHelper\DeepRelationsHook->run(Object(Barryvdh\LaravelIdeHelper\Console\ModelsCommand), Object(App\Models\Ingredient))
```

**Comment by staudenmeir** [comment]
Please try replacing line `36` of `vendor/staudenmeir/eloquent-has-many-deep/src/IdeHelper/DeepRelationsHook.php` with this:

```php
} catch (\Throwable) {
```

**Comment by staudenmeir** [comment]
I released a new version with this fix.

**Comment by nandi95** [comment]
That did fix it, thanks.
