### ISSUE TITLE
Using with a Belongs To Many?

### ISSUE THREAD

**Issue by panthro100** [staudenmeir/eloquent-has-many-deep#204]
A `Producer` `hasOne` `Distillery`, a `Distillery` `belongsToMany` `Whiskies`.

A `Whisky` `belongsToMany` `Distillery`, a `Distillery` `belongsTo` `Producer`.

I wish to use `hasManyThrough` so, to get a  `Producer`'s `Whiskies` that `belongToMany` `Distillery`.

But how can I use `hasManyThrough` with `belongsToMany` relationship? I am aware you can specify the join keys, and I think you may be able to muck about with the pivot table, but I can't figure it out. 

Will this package help?

**Comment by staudenmeir** [comment]
Hi @panthro100,
Use this relationship:

```php
class Producer extends Model
{
    use \Staudenmeir\EloquentHasManyDeep\HasRelationships;

    public function whiskies()
    {
        return $this->hasManyDeep(Whisky::class, [Distillery::class, 'distillery_whisky']);
    }
}
```
