### ISSUE TITLE
distinct - paginate

### ISSUE THREAD

**Issue by fit-vanson** [staudenmeir/eloquent-has-many-deep#217]
Please help me check why the returned result is not the same as the result when using ->total() in paginate()

// model Domains:
![image](https://github.com/staudenmeir/eloquent-has-many-deep/assets/84125055/efcc5cbd-47e1-43fc-9dd6-b42d71b9a420)
//model Tags
![image](https://github.com/staudenmeir/eloquent-has-many-deep/assets/84125055/83bed6bd-277f-46d3-9655-07b49cee78e8)

//controller:
![image](https://github.com/staudenmeir/eloquent-has-many-deep/assets/84125055/2e5db051-79ad-474b-a085-2a23135f14d5)
//result
![image](https://github.com/staudenmeir/eloquent-has-many-deep/assets/84125055/0c38d0af-9f65-42b8-8414-04ed3a9b4519)

**Comment by staudenmeir** [comment]
Hi @fit-vanson,
Unfortunately, this topic is quite complex (and annoying). Please remove `->distinct()` and try this instead:

```php
$query = $domain->wallpapers($isBlock)
    ->where(...)
    ->getQuery()
    ->select('wallpapers.*')
    ->groupBy('wallpapers.id')
    ->paginate(...);
```
