### ISSUE TITLE
Table aliases in hasManyDeepFromRelation

### ISSUE THREAD

**Issue by hogggerty** [staudenmeir/eloquent-has-many-deep#22]
I have 2 hasManyDeep relations, where i use table aliases and both work great. But if i try to create new relation from this two via hasManyDeepFromRelation, table aliases disappear from query and i get an error: SQLSTATE[42000]: Syntax error or access violation: 1066 Not unique table/alias.

Is it possible to add table aliases to hasManyDeepFromRelation?

**Comment by staudenmeir** [comment]
`hasManyDeepFromRelations()` is only meant for Laravel's "default" relationships, it doesn't support `HasManyDeep` relationships at the moment (with or without alias).

Can you create the combined relationship by concatenating/merging the arguments of the two `HasManyDeep` relationships?

**Comment by hogggerty** [comment]
Yes thank you. I already did as you wrote. 

Do you planned to realize that feature at the future?

**Comment by staudenmeir** [comment]
I'll take a look at it.

**Comment by staudenmeir** [comment]
The latest release supports `hasManyDeepFromRelations()` with `HasManyDeep` relationships.
