### ISSUE TITLE
HasOneDeep is not generic

### ISSUE THREAD

**Issue by ahoiroman** [staudenmeir/eloquent-has-many-deep#223]
I got this relation:

```
    /**
     * @return HasOneDeep<Key>
     */
    public function key(): HasOneDeep
    {
        return $this->hasOneDeepFromRelations($this->vault(), (new Vault())->key());
    }
```

But unfortunately, phpstan reports:

```
phpstan: PHPDoc tag @return contains generic type Staudenmeir\EloquentHasManyDeep\HasOneDeep<App\Models\Key> but class Staudenmeir\EloquentHasManyDeep\HasOneDeep is not generic.
```

What can I do about it?

**Comment by staudenmeir** [comment]
Hi @ahoiromanm
Does the issue go away if you add this comment to `vendor/staudenmeir/eloquent-has-many-deep/src/HasOneDeep.php`?

```php
/**
 * @template TRelatedModel of \Illuminate\Database\Eloquent\Model
 * @extends \Illuminate\Database\Eloquent\Relations\HasOneThrough<TRelatedModel>
 */
class HasOneDeep extends HasManyDeep
{
```

**Comment by ahoiroman** [comment]
Hi Jonas,

unfortunately it is not solving the problem. The error is exactly the same.

**Comment by staudenmeir** [comment]
Could be a caching issue, it works for me. Please run `vendor/bin/phpstan clear-result-cache` and try again.

**Comment by ahoiroman** [comment]
You are right. After clearing the cache it works with the changes you described.

**Comment by staudenmeir** [comment]
Great. I've released a new version with the comment.
