### ISSUE TITLE
Laravel 11

### ISSUE THREAD

**Issue by hamrak** [staudenmeir/eloquent-has-many-deep#224]
Is possible to update dependency staudenmeir/eloquent-has-many-deep-contracts to v1.2 in new release?

**Comment by hamrak** [comment]
@staudenmeir  Exactly! We are already preparing our application for new Laravel 11 and we would like it, if you would add support for v1.2 as well, when you have already released it.

```
        "illuminate/database": "^10.0|^11.0",
        "staudenmeir/eloquent-has-many-deep-contracts": "^1.1|^1.2"
```

**Comment by staudenmeir** [comment]
I'm still working on a version for Laravel 11. I've pushed the current state of development into the `l11` branch. You can test it by updating the package's version in your `composer.json` to `dev-l11`.

**Comment by staudenmeir** [comment]
I've added a version alias for the `l11` branch, so you can revert the `composer.json` entry back to `^1.7` and run `composer update`.
