### ISSUE TITLE
CompositeKey not included when installed.

### ISSUE THREAD

**Issue by webdevomandam** [staudenmeir/eloquent-has-many-deep#225]
Failed to read the CompositeKey when using the `use Staudenmeir\EloquentHasManyDeep\Eloquent\CompositeKey;`.
Also tried to check the vendor\staudemeir\eloquent-has-many-deep\src and no eloquent\* files were found.

Installed the package with this command `composer require staudenmeir/eloquent-has-many-deep:"^1.7"` and currently using laravel 6.

**Comment by staudenmeir** [comment]
Hi @webdevomandam,
Composite keys are only supported with Laravel 9+. I'll add that to the README.

**Comment by webdevomandam** [comment]
Ah I see. Thanks for the clarification. So, what can be the alternative for CompositeKey? Will array() be okay?

**Comment by staudenmeir** [comment]
There is no alternative, you can only use this feature after upgrading to Laravel 9+.
