### ISSUE TITLE
Add withCount in hasManyDeepFromRelations

### ISSUE THREAD

**Issue by luccui000** [staudenmeir/eloquent-has-many-deep#236]
Hi @staudenmeir, can you add a function so that I can use withCount for hasManyDeepFromRelations?

**Comment by staudenmeir** [comment]
Hi @luccui000,
How do you mean? How exactly do you want to use `withCount()`?

**Comment by luccui000** [comment]
Sorry for replying late !

For example, I have a relationship user -> hasOne -> favourite -> hasMany -> products. Now, I want to count the number of products for that user: $user->withCount([‘products’]). It will be something like that.
