### ISSUE TITLE
query builder

### ISSUE THREAD

**Issue by hasensuadik39** [staudenmeir/eloquent-has-many-deep#24]
how can i write query builder on this package for each spesfic model like where clause for columuns

**Comment by staudenmeir** [comment]
Please provide more details and an example.

**Comment by hasensuadik39** [comment]
when i write a where clause  at the end of hasmany deep laravel says ambigous on what table

**Comment by staudenmeir** [comment]
Try adding the table name: `->where('table.column', 'value')`

**Comment by hasensuadik39** [comment]
you know the first argument on the where clause is column name how can i use tablename

**Comment by staudenmeir** [comment]
Prefix the column name with the table name and a `.`: `->where('users.name', 'value')`

**Comment by hasensuadik39** [comment]
ya it works can i get your facebook or other social media links

**Comment by staudenmeir** [comment]
I don't have public social media.
