### ISSUE TITLE
hasManyDeep with 4 level doesn't work

### ISSUE THREAD

**Issue by bhattji** [staudenmeir/eloquent-has-many-deep#242]
I am trying to access the 4th table, but it gives errors
cities.city_id doesn't exists. but why should it look for city_id in cities table? it should look for id

```
//hasManyDeeo
    public function asset_depreciations()
    {
        return $this->hasManyDeep(AssetDepreciation::class, [City::class, Location::class, Asset::class]);
    }
```

**Comment by staudenmeir** [comment]
Hi @bhattji,
Please share the migrations of all tables involved in this relationship. In which model is the `asset_depreciations` relationship defined?
