### ISSUE TITLE
HasManyDeep::one() Doesn't Seem To Work As Expected

### ISSUE THREAD

**Issue by MannikJ** [staudenmeir/eloquent-has-many-deep#249]
I encountered errors when trying to convert a HasManyDeep relation to a HasOneX relation although the HasManyDeep relation itself works. The "one"-relation uses wrong column names etc.

In fact the first thing I noticed was that HasManyDeep::one() will return a HasOneThrough relation instead of HasOneDeep as I would expecet. The reason for this is that HasManyDeep does not (yet) overwrite the implementation of the one() function from its parent class HasManyThrough.

Maybe this feature was just overseen or not yet implemented.

**Comment by staudenmeir** [comment]
Hi @MannikJ,
The `one()` method is much, much newer than the package. I'll look into it.

**Comment by staudenmeir** [comment]
I released a new version with support for `HasManyDeep::one()`.

"Funnily" enough, `HasManyThrough::one()` doesn't work either (https://github.com/laravel/framework/pull/53119). It looks like nobody has tried to use it so far...

**Comment by MannikJ** [comment]
> "Funnily" enough, HasManyThrough::one() doesn't work either (https://github.com/laravel/framework/pull/53119). It looks like nobody has tried to use it so far...

:sweat_smile: 
We have often wondered whether we are the only ones using something. I'm not sure whether this is good or bad...

Thank you for addressing this so quickly!

**Comment by staudenmeir** [comment]
> I'm not sure whether this is good or bad...

Yeah...
