### ISSUE TITLE
 Is it possible to use subquery instead of in query?

### ISSUE THREAD

**Issue by season886** [staudenmeir/eloquent-has-many-deep#250]
```
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Staudenmeir\EloquentHasManyDeep\HasManyDeep;
use Staudenmeir\EloquentHasManyDeep\HasRelationships;

class OidcUser extends Model
{
    use HasRelationships;
    public function basicRoleAuthorities(): HasManyDeep
    {
        return $this->hasManyDeep(BasicRoleAuthorities::class,[BasicUserRole::class],['uid','role_id'],['id','role_id']);
    }
}
```
```

Route::get('/', function () {
    $test = OidcUser::with('basicRoleAuthorities')->where('id',400344744141520896)->get();
    return $test->toArray();
});

```
The SQL log is：
```
[2024-11-06 15:11:10] local.INFO: 8.00 ms, SQL: select * from "oidc_users" where "id" = 400344744141520896;  
[2024-11-06 15:11:10] local.INFO: 9.70 ms, SQL: select "basic_role_authorities".*, "basic_user_roles"."uid" as "laravel_through_key" from "basic_role_authorities" inner join "basic_user_roles" on "basic_user_roles"."role_id" = "basic_role_authorities"."role_id" where "basic_user_roles"."uid" in (400344744141520896);  
```
In SQL Server, the maximum number of parameters in the IN clause in the WHERE condition is 2100. Since the parameter list of the IN clause in SQL Server is composed of an expression list, the length of each expression list cannot exceed 2100

The ideal result I want is：
`select "basic_role_authorities".*, "basic_user_roles"."uid" as "laravel_through_key" from "basic_role_authorities" inner join "basic_user_roles" on "basic_user_roles"."role_id" = "basic_role_authorities"."role_id" where "basic_user_roles"."uid" in (select id from "oidc_users" where "id" = 400344744141520896);  `

**Comment by season886** [comment]
This works for me, but if there is a lot of data in the OidcUser table, there is a risk of error in the "in" statement. I suggest that the in (...) statement contains subqueries to avoid errors, or https://github.com/staudenmeir/eloquent-param-limit-fix If this can be merged into this package, I think it's also a good idea。Thank you for providing this great extension

**Comment by staudenmeir** [comment]
> I suggest that the in (...) statement contains subqueries to avoid errors

That's fundamentally different from Laravel's eager loading queries. You would need to implement that yourself.
