### ISSUE TITLE
Support table aliases with BelongsToMany relationships.

### ISSUE THREAD

**Issue by budhajeewa** [staudenmeir/eloquent-has-many-deep#26]
Assume the following entities:

- `User`
- `UserGroup`
- `Organization`

Assume the following relationships:

- `User` belongs to many `Organization`s.
- `User` belongs to many `UserGroup`s.

Given above, we need a relationship `User::organizationsOfUsersWithSharedUserGroups()`, that would return all the `Organization`s that belongs to any of the `User`s that shares `UserGroup`s with the calling `User` object.

PHP has to:

1. Start with the current `User` object,
2. get its `UserGroup`s,
3. get `User`s of those `UserGroup`s (Thus coming back to the `User` class, through the same pivot table.),
4. and get `Organization`s of those `User`s.

Following relationship definition accomplishes what I am after, with one caveat:

```php
public function organizationsOfUsersWithSharedUserGroups() {
	return $this->hasManyDeep(
		Organization::class,
		[
			'user_user_group',
			UserGroup::class,
			'user_user_group2',
			User::class,
			'organization_user',
		]
	);
}
```

The caveat being `user_user_group2` being a MySQL view defined as follows:

```mysql
CREATE
OR REPLACE
VIEW `db`.`user_user_group2` AS select
    `db`.`user_user_group`.`id` AS `id`,
    `db`.`user_user_group`.`user_id` AS `user_id`,
    `db`.`user_user_group`.`user_group_id` AS `user_group_id`
from
    `db`.`user_user_group`
```

Table `user_user_group` and view `user_user_group2` are identical.

If we replace `user_user_group2` with `user_user_group` in `User::organizationsOfUsersWithSharedUserGroups()`'s definition, we get the following error:

```mysql
SQLSTATE[42000]: Syntax error or access violation:
1066 Not unique table/alias: 'user_user_group'

(SQL:

select
	`organizations`.*,
	`user_user_group`.`user_id` as `laravel_through_key`
from
	`organizations`
	inner join `account_user`
		on `account_user`.`account_id` = `organizations`.`id`
	inner join `users`
		on `users`.`id` = `account_user`.`user_id`
	inner join `user_user_group`
		on `user_user_group`.`user_id` = `users`.`id`
	inner join `user_groups`
		on `user_groups`.`id` = `user_user_group`.`user_group_id`
	inner join `user_user_group`
		on `user_user_group`.`user_group_id` = `user_groups`.`id`
where
	`users`.`deleted_at` is null
	and `user_groups`.`deleted_at` is null
	and `user_user_group`.`user_id` = 1
	and `organizations`.`deleted_at` is null
)
```

I tried to specify an `as` in `User::organizationsOfUsersWithSharedUserGroups()`'s definition as follows, but it did not work.

```php
public function organizationsOfUsersWithSharedUserGroups() {
	return $this->hasManyDeep(
		Organization::class,
		[
			'user_user_group',
			UserGroup::class,
			'user_user_group as alias',
			User::class,
			'organization_user',
		]
	);
}
```

Thus, I would like to propose supporting table aliases with BelongsToMany relationships.

**Comment by budhajeewa** [comment]
I managed to find a solution by browsing through the old closed issues of this repo.

See https://github.com/staudenmeir/eloquent-has-many-deep/issues/15#issuecomment-443008581 .

Following it's instructions, I created a pivot class for the `user_user_group` pivot table, classes can be aliased without an issue!

Here is my final relationship method:

```php
public function organizationsOfUsersWithSharedUserGroups() {
	return $this->hasManyDeep(
		Organization::class,
		[
			UsersAndUserGroupsRelationship::class,
			UserGroup::class,
			UsersAndUserGroupsRelationship::class . ' as alias',
			User::class,
			'organization_user',
		]
	);
}
```

Here's the `UsersAndUserGroupsRelationship` class:

```php
use Illuminate\Database\Eloquent\Relations\Pivot;
use Staudenmeir\EloquentHasManyDeep\HasTableAlias;

class UsersAndUserGroupsRelationship extends Pivot
{
    use HasTableAlias;
    
    protected $table = 'user_user_group';
}
```

I'll leave the issue open, in case @staudenmeir might want to update the `README.md` or do something else with this issue.

**Comment by staudenmeir** [comment]
Yes, aliasing a pivot table requires a custom model. I'll add an example to the README.

**Comment by budhajeewa** [comment]
@staudenmeir : Thank you! :+1: :smiley:
