### ISSUE TITLE
Merge HasManyDeep on MorphMany at different levels

### ISSUE THREAD

**Issue by diamondobama** [staudenmeir/eloquent-has-many-deep#29]
**Scenario:**

I have `Institution -> Departments -> Qualifications -> Courses` and both `Qualification` and `Course` morph `Group`. I want to load all groups for an institution.

**I tried:**

    /**
     * Get all of the Institution's groups.
     */
    public function groups()
    {
        return $this->hasManyDeepFromRelations(
            $this->qualificationsGroups(), $this->coursesGroups()
        );
    }
    
    /**
     * Get all of the Institution's qualifications' groups.
     */
    public function qualificationsGroups()
    {
        return $this->hasManyDeep(
            Group::class,
            [Department::class . " as d1", Qualification::class . " as q1"],
            [null, null, ['groupable_type', 'groupable_id']]
        );
    }
    
    /**
     * Get all of the Institution's courses' groups.
     */
    public function coursesGroups()
    {
        return $this->hasManyDeep(
            Group::class,
            [Department::class . " as d2", Qualification::class . " as q2", Course::class],
            [null, null, null, ['groupable_type', 'groupable_id']]
        );
    }
    
**Issue:**

_SQLSTATE[42000]: Syntax error or access violation: 1066 Not unique table/alias: 'groups' (SQL: select count(*) as aggregate from `groups`........_

**Question:**
How do I resolve this or any other approach to loading groups for both courses and qualifications under an institution?

**Comment by staudenmeir** [comment]
The package doesn't support the merging of relationships. `hasManyDeepFromRelations()` is only meant for concatenating them.

Please take a look at the workaround in #17. You should be able to achieve this with a view, a `UNION` query and a `HasMany` relationship.

Does this help you? Feel free to ask if my suggestion is unclear, I know it's quite abstract.

**Comment by staudenmeir** [comment]
I'm also working on a package to simplify this.

**Comment by diamondobama** [comment]
Thanks for your response. I'm trying to avoid complex raw query in solving this and I guess I will have to do it that way.

**Comment by staudenmeir** [comment]
I've released the package: https://github.com/staudenmeir/laravel-merged-relations

First, create the merge view in a migration:

```php
use Staudenmeir\LaravelMergedRelations\Facades\Schema;

Schema::createMergeView(
    'all_groups', [(new Institution)->qualificationsGroups(), (new Institution)->coursesGroups()]
);
````

If you want to get unique results:

```php
use Staudenmeir\LaravelMergedRelations\Facades\Schema;

Schema::createMergeViewWithoutDuplicates(
    'all_groups', [(new Institution)->qualificationsGroups(), (new Institution)->coursesGroups()]
);
````

Then define the relationship:

```php
class Institution extends Model
{
    use \Staudenmeir\LaravelMergedRelations\Eloquent\HasMergedRelationships;

    public function groups()
    {
        return $this->mergedRelationWithModel(Group::class, 'all_groups');
    }
}
````

**Comment by diamondobama** [comment]
Thank you :)
