### ISSUE TITLE
Query hasManyDeep

### ISSUE THREAD

**Issue by JoeDawson** [staudenmeir/eloquent-has-many-deep#3]
Hello, me again... (sorry!)

I currently have have the following relation setup on my `Collective` model (as per #2)

```php
public function videos()
{
    return $this->hasManyDeep(Video::class, [Artist::class, 'artist_video'])->groupBy('videos.id');
}
```

How can I query this relation? I'm currently trying the following:

```php
$collective->videos()->where('slug', 'my-slug')->first();
```

However I'm receiving the following error:

> Integrity constraint violation: 1052 Column 'slug' in where clause is ambiguous (SQL: select `videos`.*, `artists`.`collective_id` from `videos` inner join `artist_video` on `artist_video`.`video_id` = `videos`.`id` inner join `artists` on `artists`.`id` = `artist_video`.`artist_id` where `artists`.`collective_id` = 1 and `slug` = my-slug group by `videos`.`id` limit 1)

Any ideas how I can get this to work?

Thanks in advance!

**Comment by staudenmeir** [comment]
Looks like you have to specify the table name:

```php
->where('videos.slug', 'my-slug')
```

**Comment by JoeDawson** [comment]
Hi @staudenmeir,

Unfortunately I get a different error with that.

> Syntax error or access violation: 1055 Expression #17 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'my-db.artists.collective_id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by (SQL: select `videos`.*, `artists`.`collective_id` from `videos` inner join `artist_video` on `artist_video`.`video_id` = `videos`.`id` inner join `artists` on `artists`.`id` = `artist_video`.`artist_id` where `artists`.`collective_id` = 1 and `videos`.`slug` = my-slug group by `videos`.`id` limit 1)

I can get it to work if I remove `->groupBy('videos.id')` from my relation, however I it to remove duplicate models as per #2.

Any ideas? Thank you!

**Comment by staudenmeir** [comment]
That's the problem discussed in #2.

Do you even need `->groupBy()` when you use `->first()`? Does that make a difference?

**Comment by JoeDawson** [comment]
Sorry I might have confused it by raising #2 in conversation.

The reason for `$collective->videos()->where('slug', 'my-slug')->first();` is because I am using route model binding and want to ensure that when someone visits the following route, the video belongs to a collective.

```php
/collectives/{collective}/videos/{video}
```

Then my route model binding looks like this - you can ignore the artist/channel code, I just left it here so you have a little bit more of an understanding of my application;

```php
Route::bind('video', function($value, $route)
{
    if(array_key_exists('artist', $route->parameters())) {
        return $route->artist->videos()->where('slug', $value)->first();
    }

    if(array_key_exists('channel', $route->parameters())) {
        return $route->channel->videos()->where('slug', $value)->first();
    }

    if(array_key_exists('collective', $route->parameters())) {
        return $route->collective->videos()->where('slug', $value)->first();
    }

    return \App\Video::where('slug', $value)->first();
});
```

I need the `->groupBy()` so that when you visit a collective in my application, you don't see duplicate videos.

Hope that's a little clearer?

**Comment by staudenmeir** [comment]
I don't see why you would have to group the videos. If you only select the first video, the result is the same in both cases. Did you try it without `->groupBy()`?

**Comment by JoeDawson** [comment]
> I don't see why you would have to group the videos.

That was to resolve my issue in #2 

However, I have removed that from my relationship now so I can query the collection and just implemented the `groupBy()` where necessary.

Thanks.
