### ISSUE TITLE
Three levels possible?

### ISSUE THREAD

**Issue by BasvanH** [staudenmeir/eloquent-has-many-deep#31]
Hello,

I'm a bit new to Eloquent and I'm still learning how to use it. Would the following be possible with your extension?

https://laracasts.com/discuss/channels/eloquent/multiple-layers?page=1#reply=509652

Much appreciated, regards,
Bastiaan

**Comment by BasvanH** [comment]
I think it comes down to:
`Customer -> hasMany -> Products -> hasOne -> Product`

**Comment by staudenmeir** [comment]
You can use my package, but you don't have to.

The answer on Laracasts is correct: Laravel's native `BelongsToMany` relationship is meant for cases like this.

**Comment by BasvanH** [comment]
Ok, have deep-dived into `belongsToMany`, but can't see this working for me. This is offcourse off topic from your beautiful package, but would you mind taking another look at the Laracasts topic? Have updated my post there. Much appreciated!
