### ISSUE TITLE
Filter hasOneDeep

### ISSUE THREAD

**Issue by fabricecw** [staudenmeir/eloquent-has-many-deep#33]
Is there a way to use the `whereHas` method properly with a `hasOneDeep` instance?

The pivot table:

| order_id | status_id | step | completed_at | 
| --- | ---| ---| ---| 
| 1 | 1 | 10 | 2019-0706 16:00 | 
| 1 | 2 | 20 | null | | 1 | 3 | 30 | null |
| 1 | 3 | 30 | null | | 1 | 3 | 30 | null |
| 1 | 7 | 40 | null | | 1 | 3 | 30 | null |
| 1 | 5 | 50 | null | | 1 | 3 | 30 | null |

I use the relationship like:
```
public function lastCompletedStatus()
    {
        return $this->hasOneDeep(Status::class, [OrderStatus::class])
            ->where('completed_at', '!=', null)
            ->latest('step');
    }
```

But if I filter through this relation:
```
$orders = $orders->whereHas('lastCompletedStatus', function($query){
            $query->where('description', 'order_checked');
        });
```

It gives me a collection with all orders completed the given status. But I want to filter for orders in this specific status. Is this even possible?

**Comment by staudenmeir** [comment]
No, that's not possible with `whereHas()` (i.e. SQL subqueries).

It requires a more complex JOIN query: https://stackoverflow.com/a/53120558/4848587
