### ISSUE TITLE
belongsToMany and BelongsTo ?

### ISSUE THREAD

**Issue by ganuonglachanh** [staudenmeir/eloquent-has-many-deep#34]
Hi, I have relationships like this: 
`User →  belongsToMany Product →  BelongsTo Customer`

User Table: user.id

Product Table :
---- product.id
---- product.customer_id

Pivot table:
---- product_user.user_id
---- product_user.product_id

Customer Table:
customer.id

Does **eloquent-has-many-deep** support this? I only found this similar but for morphed by many:
`Tag → morphed by many → Post → belongs to → User `

How can I get `user->customer()` and reverse: `customer->user()` ?

Thank you!

**Comment by staudenmeir** [comment]
Yes, this is supported:

```php
class User extends Model
{
    use \Staudenmeir\EloquentHasManyDeep\HasRelationships;

    public function customers()
    {
        return $this->hasManyDeep(
            Customer::class,
            ['product_user', Product::class],
            [null, null, 'id'],
            [null, null, 'customer_id']
        );
    }
}

class Customer extends Model
{
    use \Staudenmeir\EloquentHasManyDeep\HasRelationships;

    public function users()
    {
        return $this->hasManyDeep(User::class, [Product::class, 'product_user']);
    }
}
```
