### ISSUE TITLE
Global model scopes ignored in HasManyDeep

### ISSUE THREAD

**Issue by brynj-digital** [staudenmeir/eloquent-has-many-deep#35]
I have global scopes that are applied in the boot() method of some of my models in a HasManyDeep relationship. 

It seems like these are being ignored - in effect, I'm getting data that I shouldn't be because my model 'active' property is being ignored.

Is this expected behaviour, or should global scopes apply in intermediate models?

**Comment by staudenmeir** [comment]
It's not ideal, but it's the expected behavior. Of the intermediate models' global scopes, only `SoftDeletes` is applied. I chose this behavior to match Laravel's native `HasManyThrough` relationship (https://github.com/laravel/framework/issues/23039#issuecomment-414184128).

You'll need to apply these global scopes manually.

**Comment by brynj-digital** [comment]
Thank you for the prompt reply and clarification - it's useful to confirm it as expected behaviour, and I will ensure I deal with these instances appropriately.

**Comment by LonnyX** [comment]
@staudenmeir is it normal that withTrashed() doesn't works on this case?
I understand that `SoftDeletes` is applied automatically but how can we prevent this?

**Comment by staudenmeir** [comment]
@LonnyX Did you see https://github.com/staudenmeir/eloquent-has-many-deep#soft-deleting?

**Comment by LonnyX** [comment]
Oops, I commented on the wrong rep, sorry. 
Thank you for this package. 
I wonder why this is still not fixed by Laravel :/

**Comment by peterthomson** [comment]
This caused me a foot gun. But Staudenmeir is right. Ignoring global scopes is the framework behaviour and this package mirrors it. Just something for us all to keep an eye on.
