### ISSUE TITLE
support eager-limit?

### ISSUE THREAD

**Issue by rick20** [staudenmeir/eloquent-has-many-deep#39]
Hi, does `hasOneDeep()` supports `HasEagerLimit` ?
The docs said that it supports laravel's basic relationships `HasOne`/`HasOneThrough`/`MorphOne` but I'm using your `hasOneDeep` relationships.

Is it possible to use the window function from the hasOneDeep relationships?
Thank you

**Comment by rick20** [comment]
I can't use `hasOneThrough` because it doesn't allow me to include pivot columns

**Comment by staudenmeir** [comment]
I'll look into it.

**Comment by staudenmeir** [comment]
What's your Laravel version?

**Comment by rick20** [comment]
I'm using Laravel 5.8 but planned to migrate to 6

**Comment by staudenmeir** [comment]
I've released a new version that adds support for eager loading with limit.

You'll need to migrate to Laravel 6, first, it doesn't work with 5.8.

**Comment by rick20** [comment]
Hi Jonas...apologize for late reply...been busy with our client's deployment this week
And thank you for the release...I'll look into it and will certainly use it in our upcoming project.
