### ISSUE TITLE
Possibility to add a BelongsToThrough relationship

### ISSUE THREAD

**Issue by willemo** [staudenmeir/eloquent-has-many-deep#4]
Hi!

This library works like a charm! The only issue I currently have is that I'd like to define the reverse of the HasManyDeep relation, so in your example the `Comment` model having a singular `Country`. Would it be possible to add this relationship as well?

Cheers

**Comment by staudenmeir** [comment]
You can use the `BelongsToThrough` package: https://github.com/znck/belongs-to-through

**Comment by willemo** [comment]
I didn't realise that they allow multiple intermediate models. Thanks for the tip!
