### ISSUE TITLE
hasManyDeepFromRelation with table aliases

### ISSUE THREAD

**Issue by ockle** [staudenmeir/eloquent-has-many-deep#40]
This was already brought up in #22, but that ticket went in a different direction. Can table aliases be used with `hasManyDeepFromRelations`?

**Comment by staudenmeir** [comment]
What do your individual relationships look like?

**Comment by ockle** [comment]
This is essentially what I'm doing:

```php
class User extends Model
{
    public function lowerLevels()
    {
        return $this->belongsToMany(LowerLevel::class);
    }

    public function allLowerLevelsBelongingToAllLowerLevelsUpperLevels()
    {
        return $this->hasManyDeepFromRelations($this->lowerLevels(), (new LowerLevel)->upperLevel(), (new UpperLevel)->lowerLevels());
}

class LowerLevel extends Model
{
    public function upperLevel()
    {
        return $this->belongsTo(UpperLevel::class);
    }
}

class UpperLevel extends Model
{
    public function lowerLevels()
    {
        return $this->hasMany(LowerLevel::class);
    }
}
```

**Comment by staudenmeir** [comment]
You need to define a "real" `HasManyDeep` relationship:

```php
class User extends Model
{
    public function allLowerLevelsBelongingToAllLowerLevelsUpperLevels()
    {
        return $this->hasManyDeep(
            LowerLevel::class,
            ['lower_level_user', LowerLevel::class.' as alias', UpperLevel::class],
            [null, null, 'id'],
            [null, null, 'upper_level_id']
        );
    }
}

class LowerLevel extends Model
{
    use \Staudenmeir\EloquentHasManyDeep\HasTableAlias;
}
```

**Comment by ockle** [comment]
That does indeed work, thanks :)

However I find it much harder to work out how to construct the relationship that way. I feel like the `hasManyDeepFromRelations` method that you can pass a chain of existing relationships in, in the exact chain order, and it "magically" works, is the stand out feature of this fantastic package. If every example can be implemented via `hasManyDeepFromRelations`, then I would think that should be shown as the primary way of using the package, with `hasManyDeep` as the fallback for any edge cases that can't, such as this.

Having said that, is there any way something like the following could be made to work:
```php
$lowerLevel = new LowerLevel;
$lowerLevel->setTable($lowerLevel->getTable() . ' as table_alias');
$this->hasManyDeepFromRelations($this->lowerLevels(), $lowerLevel->upperLevel(), (new UpperLevel)->lowerLevels());
```
or as as an additional method in the `HasTableAlias` trait:
```php
$this->hasManyDeepFromRelations($this->lowerLevels(), (new LowerLevel)->alias('table_alias')->upperLevel(), (new UpperLevel)->lowerLevels());
```
and `hasManyDeepFromRelations` then pick up the table name to use from there?

**Comment by staudenmeir** [comment]
Yeah, that's not ideal. I've looked into alternatives like automatic aliasing of duplicate tables, but haven't found a good solution yet. I'll try again and consider your suggestions.

**Comment by staudenmeir** [comment]
I've released a new version that adds the `setAlias()` method (requires Laravel 6):

```php
return $this->hasManyDeepFromRelations(
    $this->lowerLevels(),
    (new LowerLevel)->setAlias('table_alias')->upperLevel(),
    (new UpperLevel)->lowerLevels()
);
```

**Comment by oscar-schwarz** [comment]
I stumbled upon this issue having the exact problem, though trying your `setAlias` solution throws an error. I use Laravel 9 and `(new Model)->setAlias()` is not defined.
