### ISSUE TITLE
hasManyDeepJson ?

### ISSUE THREAD

**Issue by raphaelmsr** [staudenmeir/eloquent-has-many-deep#42]
Hi, your work saved my life in terms of Eloquent Relationships everything that I needed was related to you on github 🥇 
I wonder if it would be possible to have a hasManyDeepJson kind of hybrid like this :

`
class Mapregion extends Model {  
public function groups()  
   {  
      return $this->hasManyDeepJson('Models\Group', ['Models\Subregion', 'address->hq->country_id']);
   }  
}  
`
thanks a lot

**Comment by staudenmeir** [comment]
Can you provide the migrations of all three tables?

**Comment by staudenmeir** [comment]
You can actually achieve this with a `HasManyDeep` relationship:

```php
class Mapregion extends Model
{
    use \Staudenmeir\EloquentHasManyDeep\HasRelationships;

    public function groups()
    {
        return $this->hasManyDeep(
            Group::class,
            [Subregion::class, Country::class],
            [null, null, 'address->hq->country_id']
        );
    }
}
```

**Comment by raphaelmsr** [comment]
Thanks for your amazing reply, I believe we made progress because now I have an error : Undefined function: 7 ERROR: operator does not exist: integer = text LINE 1: ...nner join "GEO_COUNTRIES" on "GEO_COUNTRIES"."id" = "HOT_GRO... 

But my id in the dictionary is indeed an integer and I find no way to manipulate the datatype or to be sure that the relation works; bc whatever I write after 'address->****' in the model; it is the same error

**Comment by staudenmeir** [comment]
I had only tested it on MySQL. I'll try to make it work on PostgreSQL.

**Comment by raphaelmsr** [comment]
Thank you so much; but tbh don't bother since I could use a HasJsonRelationships on Subregion instead; so everytime I need Mapregion to Group, I count on Subregion.
 
That was the origin of my question; if it was possible to do a HasManyDeep but in JSON;indeed in Postgre it could be different

**Comment by staudenmeir** [comment]
Yes, JSON queries on PostgresQL require adjustments and they aren't trivial.

If you can find a different solution, that would be great.
