### ISSUE TITLE
relation between 3 tabels

### ISSUE THREAD

**Issue by mRamadan0101** [staudenmeir/eloquent-has-many-deep#43]
i have 3 table and want to make relation between them 

order:
id,total

order_details:
order_id
dish_name

extra_items
id
title

order_details_extra_items
order_details_id
extra_items_id

how can make relation between them in Order Model؟
i try to use this function

    public function order_details_extra()
    {
        return $this->hasManyDeep(
            'App\Models\OrderDetails',
            ['order_details_extra_items', 'App\Models\ExtraItems'], 
            [           
               'order_details_id',
               'id',   
               'order_id'  
            ],
            [          
              'id',    
              'extra_items_id', 
              'id'     
            ]
        );
    }

**Comment by staudenmeir** [comment]
Use this relationship:

```php
public function order_details_extra()
{
    return $this->hasManyDeep(
        'App\Models\ExtraItems',
        ['App\Models\OrderDetails', 'order_details_extra_items']
    );
} 
```

**Comment by mRamadan0101** [comment]
need to defined column 
'order_details_id','extra_items_id' 
where

**Comment by staudenmeir** [comment]
This shouldn't be necessary, you are using the Laravel conventions for naming columns.

Do you get an error?

**Comment by mRamadan0101** [comment]
no error but no data added

**Comment by staudenmeir** [comment]
What does your query look like?

**Comment by mRamadan0101** [comment]
$form->multipleSelect('order_details_extra', 'Extra Items')->options(ExtraItems::all()->pluck('title', 'id'));

**Comment by staudenmeir** [comment]
Where does `multipleSelect()` come from?

**Comment by mRamadan0101** [comment]
Laravel Admin
https://laravel-admin.org/docs

**Comment by staudenmeir** [comment]
Please try a simple query like `dd(Order::find($id)->order_details_extra);` first.

**Comment by mRamadan0101** [comment]
null

**Comment by mRamadan0101** [comment]
i add manual data and displayed 
dd(Order::find($id)->order_details_extra);

**Comment by staudenmeir** [comment]
What's the result of `dd(Order::find($id)->order_details_extra());`?

**Comment by mRamadan0101** [comment]
too many data 
started from order_details
