### ISSUE TITLE
withIntermediate eager loading relationships

### ISSUE THREAD

**Issue by King-Aardvark** [staudenmeir/eloquent-has-many-deep#44]
The filtering is working as expected but, is there any way to eager load relationships for a intermediate/pivot table?
```
public function teachers()
{
       return $this->hasManyDeepFromRelations($this->enrolments(), (new Enrolment())->user())
                    ->withIntermediate(Enrolment::class)
                    ->where('request_status', 'Approved') //Filter by Enrolment column
                    ->with('school')               //Enrolment model relationship (Doesn't work)
                    ->with('enrolment.school')     //I have also tried this (Doesn't work)
                    ->with('courses')           //User model relationship (Works)
                    ->whereHas('roles', function ($query) { //Filter by user.roles column
                        $query->where('name', 'teacher');
                    });
}
```
I tried this as well but I see that hasManyDeepFromRelations doesn't preserve  additional constraints. https://github.com/staudenmeir/eloquent-has-many-deep/issues/36#issuecomment-519950021
```
public function enrolments()
{
        return $this->hasManyThrough(
            Enrolment::class,
            CourseSchool::class,
            'course_id',
            'course_school_id'
        )
                    ->with('school'); //Also doesn't work
                    
}
```

**Comment by staudenmeir** [comment]
How are you using the `teachers` relationship?

**Comment by King-Aardvark** [comment]
The goal was to be able to send a query like this to my API. 
`/api/courses?include=teachers,students&filter[fullname]=Chemistry%209`
[Query builder](https://github.com/spatie/laravel-query-builder) to resolve the includes to relationships. 

Course ( Contains teachers() )
|  
CourseSchool   -> School (This is the relationship I want to eager load)
|  
Enrolment
|  
User
|
Roles

**Comment by staudenmeir** [comment]
It's only possible with lazy eager loading:

```php
$courses = Course::with('teachers')->get();

$teachers = $courses->pluck('teachers')->flatten();

$teachers->load('enrolment.school');
```

**Comment by King-Aardvark** [comment]
I will give it a shot. Thank you for the insight.
