### ISSUE TITLE
Error in the README

### ISSUE THREAD

**Issue by raphaelmsr** [staudenmeir/eloquent-has-many-deep#45]
I think there's a typo, otherwise I didn't catch the `belongsToMany` paragraph

Its written 
` public function permissions()
    {
        return $this->hasManyDeep('App\Permission', ['role_user', 'App\Role']);
    }`

Shouldn't it be 
` public function permissions()
    {
        return $this->belongsToMany('App\Permission', ['role_user', 'App\Role']);
    }`
 ?

**Comment by staudenmeir** [comment]
The code is correct: It shows how you can use the package to combine a `BelongsToMany` and a `HasMany` relationship into a single `HasManyDeep` relationship.

**Comment by raphaelmsr** [comment]
So the belongsToMany is only between User and Role; the hasManyDeep is applied to the parent level ?

**Comment by staudenmeir** [comment]
Imagine your application has these models and relationships:

```php
class User extends Model
{
    public function roles()
    {
        return $this->belongsToMany('App\Role', 'role_user');
    }
}

class Role extends Model
{
    public function permissions()
    {
        return $this->hasMany('App\Permission');
    }
}
```

You can use this package to define a direct relationship from `User` to `Permission`:

```php
class User extends Model
{
    use \Staudenmeir\EloquentHasManyDeep\HasRelationships;

    public function permissions()
    {
        return $this->hasManyDeep('App\Permission', ['role_user', 'App\Role']);
    }
}
```

**Comment by raphaelmsr** [comment]
Magnificent, so there is no real HasManyDeep inverse relationship in a way?
Thank you so much again

**Comment by staudenmeir** [comment]
From `Permission` to `User`? You can also use this package to define the inverse relationship.

**Comment by raphaelmsr** [comment]
So the same hasManyDeep ? Similar to the inverse of belongsToMany, it is the same relationship ?

**Comment by staudenmeir** [comment]
It would look like this:

```php
class Permission extends Model
{
    use \Staudenmeir\EloquentHasManyDeep\HasRelationships;

    public function users()
    {
        return $this->hasManyDeep(
            'App\User',
            ['App\Role', 'role_user'],
            ['id'],
            ['role_id']
        );
    }
}
```

**Comment by raphaelmsr** [comment]
Even without a pivot table ? In a case where I don't have a belongstoMany in the middle

**Comment by staudenmeir** [comment]
What's your actual relationship?

**Comment by raphaelmsr** [comment]
`Mapregion` -> hasMany -> `Subregion` -> hasMany -> `Country` -> hasMany -> `Group`
And then Country hasMany Groups, Brands, and Units as well;
Each child belongs to its Parent; its pretty straightforward (a single subregion belongs to a single mapregion; a single brand belongs to a single group; etc)  

I wanted a HasManyDeep between Mapregion and Group; Brand and Unit (using hasManyDeepFromRelations)

If i wanted to get the Mapregion of a single group; since it belongs to only one; what would be the relationship ? I I use your `belongsToThrough` for now but I may be wrong

**Comment by staudenmeir** [comment]
In this case, a `BelongsToThrough` relationship is indeed the easiest solution.

**Comment by raphaelmsr** [comment]
Your packages are life-saving; for real :) Thanks!
