### ISSUE TITLE
belongsTo through hasMany

### ISSUE THREAD

**Issue by plakhin** [staudenmeir/eloquent-has-many-deep#46]
Is this possible using this package?

`User` → hasMany → `Campaign` → belongsTo → `Template`.

I need `$user->templates`.

now I use:
```
public function getTemplatesAttribute()
{
    return $this->campaigns->map->template;
}
```
But this is just a Collection, not relationship.

Thanks!

**Comment by plakhin** [comment]
Also interested in `User` → hasMany → `Campaign` → belongsToMany → `Template`.

**Comment by staudenmeir** [comment]
Please post the structure/migrations of all tables involved.

**Comment by plakhin** [comment]
At the moment I'm out of the office already, so can't copy/paste. But I can tell that these 3 cases are separate cases and each uses default Laravel conventions for tables, columns, foreign keys and pivot tables naming.

**Comment by staudenmeir** [comment]
> User → hasMany → Campaign → belongsTo → Template

This is a standard `BelongsToMany` relationship with `campaigns` as the pivot table.

> User → hasMany → Campaign → belongsToMany → Template

```php
class User extends Model
{
    use \Staudenmeir\EloquentHasManyDeep\HasRelationships;

    public function templates()
    {
        return $this->hasManyDeep(Template::class, [Campaign::class, 'campaign_template']);
    }
}
```

> User → belongsToMany → Campaign → belongsToMany → Template

```php
class User extends Model
{
    use \Staudenmeir\EloquentHasManyDeep\HasRelationships;

    public function templates()
    {
        return $this->hasManyDeep(
            Template::class,
            ['campaign_user', Campaign::class, 'campaign_template']
        );
    }
}
```

**Comment by plakhin** [comment]
This is awesome!
Thank you very much!

**Comment by plakhin** [comment]
@staudenmeir can you please help with this relationship?

`Team` → belongsToMany → `Domain` → hasMany → `Campaign` → belongsTo → `Template`

I nead `templates()` relationship for `Team` model. All models use default Laravel conventions for tables, columns, foreign keys and pivot tables naming.

**Comment by staudenmeir** [comment]
```php
class Team extends Model
{
    use \Staudenmeir\EloquentHasManyDeep\HasRelationships;

    public function templates()
    {
        return $this->hasManyDeep(
            Template::class,
            ['domain_team', Domain::class, Campaign::class],
            [null, null, null, 'id'],
            [null, null, null, 'template_id']
        );
    }
}
```

**Comment by plakhin** [comment]
Thank you very much
