### ISSUE TITLE
problem for multiple level of table same category 3 level

### ISSUE THREAD

**Issue by webazin90** [staudenmeir/eloquent-has-many-deep#47]
hi, im using category table multiple level, for relation of grandpa(level 1) category with product use this package witch very well and work, but relation of father(level 2) category with product not work, this relation 

` public function throughProducts()
    {
        return $this->hasManyThrough(Category::class, 'App\Models\Category', 'parent_id', 'parent_id');
    }
`
this error :

> SQLSTATE[42000]: Syntax error or access violation: 1066 Not unique table/alias: 'categories' (SQL: select count(*) as aggregate from `categories` inner join `categories` on `categories`.`id` = `categories`.`parent_id` where `categories`.`parent_id` = 2)

**Comment by staudenmeir** [comment]
> for relation of grandpa(level 1) category with product use this package witch very well and work

How is that relationship defined?

**Comment by webazin90** [comment]
hi, i think categories table not alias this error occured,

in category table 3 level exist, foreign key is parent_id, 
how in eloquent set alias for table?

laravel 6.0

**Comment by staudenmeir** [comment]
It's not possible to use `HasManyThrough` relationships with an alias.

You can define `throughProducts` with this package and [table aliases](https://github.com/staudenmeir/eloquent-has-many-deep#table-aliases).

Can you post the `Category` model?

**Comment by webazin90** [comment]
thank you very much, my category model this:
```
namespace App\Models;

use Cviebrock\EloquentSluggable\Sluggable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Relations\HasManyThrough;
use Illuminate\Database\Eloquent\Relations\MorphOne;
use Illuminate\Support\Facades\DB;
use Staudenmeir\EloquentHasManyDeep\HasManyDeep;
use Staudenmeir\EloquentHasManyDeep\HasRelationships;
use Staudenmeir\EloquentHasManyDeep\HasTableAlias;

class Category extends Model
{
    use Sluggable, HasRelationships, HasTableAlias;

    protected $fillable = ['title', 'slug', 'seo_tag', 'seo_description', 'parent_id'];

    public const IMAGE_SIZE = ['40', '100', '200'];

    /**
     * relation category with parent category.
     * @return BelongsTo
     */
    public function parent()
    {
        return $this->belongsTo(Category::class, 'parent_id');
    }

    /**
     * relation category with children category.
     * @return HasMany
     */
    public function children()
    {
        return $this->hasMany(Category::class, 'parent_id');
    }

    /**
     * relation category with allChildren category.
     * @return HasMany
     */
    public function allChildren()
    {
        return $this->children()->with('allChildren');
    }

    /**
     * relation category with allParent category.
     * @return BelongsTo
     */
    public function allParent()
    {
        return $this->parent()->with('allParent');
    }

    /**
     * check category has parent.
     * @return bool
     */
    public function hasParent()
    {
        return !!$this->parent;
    }

    /**
     * relation of grandpa(level 1) category with products.
     * @return HasManyDeep
     */
    public function deepProducts()
    {
        return $this->hasManyDeep(Product::class, ['App\Models\Category as alias', Category::class], [
            'parent_id', // Foreign key on the "category" table.
            'parent_id',    // Foreign key on the "category" table.
            'category_id'     // Foreign key on the "product" table.
        ], [
            'id', // Local key on the "countries" table.
            'id', // Local key on the "users" table.
            'id'  // Local key on the "posts" table.
        ]);
    }

    /**
     * relation father(level 2) with products.
     * @return HasManyThrough
     */
    public function throughProducts()
    {
        return $this->hasManyDeep(Product::class, ['App\Models\Category as alias'], ['parent_id', 'category_id']);
    }

    /**
     * relation category with image morph one to one.
     * @return MorphOne
     */
    public function image()
    {
        return $this->morphOne(Image::class, 'imageable');
    }

    /**
     * url param with slug instead id attribute.
     * @return string
     */
    public function getRouteKeyName()
    {
        return 'slug';
    }

    /**
     * Return the sluggable configuration array for this model.
     * create slug by title attribute.
     * @return array
     */
    public function sluggable(): array
    {
        return [
            'slug' => [
                'source' => 'title'
            ]
        ];
    }
}
`

thank you for this package

**Comment by staudenmeir** [comment]
Should the relationship return categories or products? It's named `throughProducts`, but only contains the `Category` model.

**Comment by AbanoubNassem** [comment]
I'm facing the same issue with `polymorphic` relationship:

```
class Reservation extends Model{
    public function discount()
    {
        return $this->morphTo();
    }
}
```

and I have two types of discounts:

```
class Discount extends Model
{
    public function reservations()
    {
        return $this->morphMany(Reservation::class, 'discount');
    }
}
```

and SpecialDiscount:

```
class SpecialDiscount extends Model
{
   public function reservations()
    {
        return $this->morphMany(Reservation::class, 'discount');
    }
}
```

and `SpecialDiscount` and `Discount` are belonging to `Restaurant`

now I'm trying to access the `Restaurant Reservations` through discounts:

in `Restaurant` model:

  ```
  public function reservations()
    {
//        return $this->hasManyThrough(Reservation::class, SpecialDiscount::class, 'restaurant_id', 'discount_id');

        return $this->hasManyDeep(
            Reservation::class,
            [SpecialDiscount::class, Discount::class, 'reservations'],
            [null, ['discount_type', 'discount_id']]
        );
    }
```

and it errors out:

`SQLSTATE[42000]: Syntax error or access violation: 1066 Not unique table/alias: 'reservations' (SQL: select `reservations`.*, `special_discounts`.`restaurant_id` as `laravel_through_key` from `reservations` inner join `reservations` on `reservations`.`reservation_id` = `reservations`.`id` inner join `discounts` on `discounts`.`id` = `reservations`.`discount_id` inner join `special_discounts` on `special_discounts`.`id` = `discounts`.`discount_id` where `discounts`.`deleted_at` is null and `discounts`.`discount_type` = App\Models\SpecialDiscount and `special_discounts`.`restaurant_id` = 5 and `reservations`.`deleted_at` is null)`

any suggestions ?

**Comment by staudenmeir** [comment]
@AbanoubNassem Can you post the structures/migrations of all tables involved?

**Comment by AbanoubNassem** [comment]
> @AbanoubNassem Can you post the structures/migrations of all tables involved?

sure

Restaurant:
```
id
title
description
etc....
```

Discount:

```
id
restaurant_id
date
percent
```

SpecialDiscount:

```
id
restaurant_id
from
to
percent
```

Reservation:

```
id
user_id
discount_id
discount_type
reserved_at
```

**Comment by staudenmeir** [comment]
It's not possible to use the package like this: You can only get the reservations through `discounts` *or* `special_discounts`. You need to define two separate relationships:

```php
public function discountReservations()
{
    return $this->hasManyThrough(
        Reservation::class, Discount::class, 'restaurant_id', 'discount_id'
    )->where('discount_type', Discount::class);
}

public function specialDiscountReservations()
{
    return $this->hasManyThrough(
        Reservation::class, SpecialDiscount::class, 'restaurant_id', 'discount_id'
    )->where('discount_type', SpecialDiscount::class);
}
```

If you want to merge these relationships, you can use one of my other packages:
https://github.com/staudenmeir/laravel-merged-relations

**Comment by AbanoubNassem** [comment]
> It's not possible to use the package like this: You can only get the reservations through `discounts` _or_ `special_discounts`. You need to define two separate relationships:
> 
> ```
> public function discountReservations()
> {
>     return $this->hasManyThrough(
>         Reservation::class, Discount::class, 'restaurant_id', 'discount_id'
>     )->where('discount_type', Discount::class);
> }
> 
> public function specialDiscountReservations()
> {
>     return $this->hasManyThrough(
>         Reservation::class, SpecialDiscount::class, 'restaurant_id', 'discount_id'
>     )->where('discount_type', SpecialDiscount::class);
> }
> ```
> 
> If you want to merge these relationships, you can use one of my other packages:
> https://github.com/staudenmeir/laravel-merged-relations

that's the problem I didn't want to do multiple queries then merge the result

**Comment by staudenmeir** [comment]
Well, it requires a complex query to get all reservations at once. The package I linked offers this feature.
