### ISSUE TITLE
Problem with custom keys in ManyToMany -> ManyToMany -> ManyToMany

### ISSUE THREAD

**Issue by ccssmania** [staudenmeir/eloquent-has-many-deep#48]
Hello!
At first, i'm really grateful to you because your package is really helpful, so thank you so much.

However, I'm a little confused when using custom keys in intermediate tables, that is because I have a relation App\User BelongsToMany App\User then the foreign keys couldn't be in the way as laravel require.
The structure of the tables are.

users :
id

responsible_user:
id - responsible_id - user_id

farms : 
id

farm_user : 
id - user_id - farm_id

the way that I need the relation is:
User -> BelongsToMany -> Users -> BelongsToMany -> Farms
I did something like:

```
public function farms(){
	return $this->hasManyDeep('App\Farm', ['responsible_user','App\User','farm_user']);
}
```

but I need to define the custom keys to responsible_user pivot table.

Thank you for your attention and sorry for disturbing you.

**Comment by staudenmeir** [comment]
> User -> BelongsToMany -> Users

Which foreign key column (`responsible_id`, `user_id`) belongs to which side of the relationship?

**Comment by ccssmania** [comment]
`user_id` belongs to the left side (user) and  `responsible_id` belongs to the right side (users)

**Comment by staudenmeir** [comment]
Use this:

```php
public function farms()
{
    return $this->hasManyDeep(
        'App\Farm',
        ['responsible_user', 'App\User', 'farm_user'],
        [null, 'id'],
        [null, 'responsible_id']
    );
}
```
