### ISSUE TITLE
(hasMany->belongTo) Which one to choose for these relationships?

### ISSUE THREAD

**Issue by nekooee** [staudenmeir/eloquent-has-many-deep#49]
Hi Dear,
I have these relations:
Article->(hasMany)Translate->(belongTo)translator
I need to Article->translators() and reverse

thanks

**Comment by staudenmeir** [comment]
Please post the two individual relationships or the structure of all three tables.

**Comment by nekooee** [comment]
translators :
```php
id
name
```

articles :
```php
id
```

article_translations (pivot) :
```php
id
locale
title
article_id
translator_id
```

I need to **Article->translators()** and reverse **Translators->articles()**

thank you

**Comment by staudenmeir** [comment]
That's a standard `BelongsToMany` relationship:
https://laravel.com/docs/eloquent-relationships#many-to-many

**Comment by nekooee** [comment]
But the translators have no direct relationship to the articles. I want to get articles with a specific translator as well as all the articles with a translator.

**Comment by staudenmeir** [comment]
> But the translators have no direct relationship to the articles.

They are connected by the pivot table.

**Comment by nekooee** [comment]
I think I got my tables wrong. I don't have a pivot table. please see this image:

![Untitled-1](https://user-images.githubusercontent.com/6003803/67087383-ae753b00-f1af-11e9-87ce-c2629f9f5252.png)
