### ISSUE TITLE
Is there any way using BelongsToThrough with hasManyDeepFromRelations

### ISSUE THREAD

**Issue by canerdogan** [staudenmeir/eloquent-has-many-deep#50]
I'm trying to using BelongsToThrough package with this package. But combining two of them it's not working. Maybe I'm missing something easy but anyway I want to get Orders -> Areas.

My Relations look like this;
---
`Order` → belongs to → `Address` → belongs to → `District` -> belongs to many -> `Area`

My Tables
---
orders

id | other_columns | address_id
-- | -------------- | -----------
1 |  Something | 1

addresses

id | other_columns | district_id
-- | --------------- | ----------
1 | Something | 1

districts

id | name
-- | ------
1 | Kadıkoy

areas

id | name
-- | -----
1 | First Area

area_district

area_id | district_id
------- | ----------
1 | 1

My Code
---
In my Order model I have `districts` relation
```php
public function districts ()
{
    return $this->belongsToThrough(District::class, Address::class);
}
```

When I add `areas` relation like this;
```php
public function areas ()
{
    return $this->hasManyDeepFromRelations($this->districts(), (new District())->areas());
}
```

I got Exceptions because in your `hasOneOrManyDeepRelationMethod` hasn't `BelongsToThrough`

Is there any way to use both? Or maybe I miss something and Can anyone help?

Thanks,
Can

**Comment by staudenmeir** [comment]
`BelongsToThrough` relationships are not supported at the moment. I'll consider it.

As a workaround, you can use a `HasOneDeep` relationship:

```php
class Order extends Model
{
    use \Staudenmeir\EloquentHasManyDeep\HasRelationships;

    public function districts()
    {
        return $this->hasOneDeep(
            District::class, [Address::class], ['id', 'id'], ['address_id', 'district_id']
        );
    }
}

hasOneThrough
```

Laravel 5.8+ offers `HasOneThrough` relationships:

```php
class Order extends Model
{
    public function districts()
    {
        return $this->hasOneThrough(
            District::class, Address::class, 'id', 'id', 'address_id', 'district_id'
        );
    }
}
```

**Comment by canerdogan** [comment]
@staudenmeir Awesome, workaround worked!

Thank you so much for your fast reply.
