### ISSUE TITLE
relation variable returns only first result

### ISSUE THREAD

**Issue by no0by5** [staudenmeir/eloquent-has-many-deep#51]
I have Users, Meetings and MeetingMails. User has a relation with Meeting and Meeting has a relation with MeetingMail. I defined the relation like this:
```
public function meetingMails(): HasManyDeep {
    return $this->hasManyDeepFromRelations(
        $this->meetings(),
        (new Meeting())->meetingMails()
    );
}
```
When is use `$user->meetingMails` to get the MeetingMails I only get the first MeetingMail. When I use `$user->meetingMails()->get()` I get all MeetingMails as excpected. Shouldn't these two code snippets do the same?

**Comment by staudenmeir** [comment]
Yes, they should. Can you please log the executed queries in both cases?

**Comment by no0by5** [comment]
I can't reproduce this bug.... I don't know why it didn't work yesterday, but it works as expected now. Thanks for the quick answer.
