### ISSUE TITLE
relation morph in hasOneDeep

### ISSUE THREAD

**Issue by mohammadgh1370** [staudenmeir/eloquent-has-many-deep#55]
hi,

thank you for this goods packages.

in this my issues 3 table exist:

service ----- one to many ----- reserve ----- morph one ----- pay

in pay model use this relation to access service of pay:
```
/**
     * relation of pay with service.
     * @return HasOneDeep
     */
    public function service()
    {
        return $this->hasOneDeep(Service::class, [Reserve::class], [null, null], [['payable_type', 'payable_id'], null]);
    }
```

this relation and forgien key is true?
if true , this error happend:

> array_key_exists(): The first argument should be either a string or an integer

**Comment by staudenmeir** [comment]
Please post the exception's stacktrace.

**Comment by mohammadgh1370** [comment]
> Illuminate\Foundation\Bootstrap\HandleExceptions::handleError :321
> C:\xampp\htdocs\reserve\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Concerns\HasAttributes.php
  
```
        // If the attribute exists in the attribute array or has a "get" mutator we will

        // get the attribute's value. Otherwise, we will proceed as if the developers

        // are asking for a relationship's value. This covers both types of values.

        if (array_key_exists($key, $this->attributes) ||

            $this->hasGetMutator($key)) {

            return $this->getAttributeValue($key);

        }
```

That's enough؟

**Comment by staudenmeir** [comment]
Please post the *whole* stacktrace. How are you using the relationship?

**Comment by mohammadgh1370** [comment]
> [2019-12-27 11:59:20] local.ERROR: array_key_exists(): The first argument should be either a string or an integer {"userId":16,"exception":"[object] (ErrorException(code: 0): array_key_exists(): The first argument should be either a string or an integer at C:\\xampp\\htdocs\
> eserve\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Eloquent\\Concerns\\HasAttributes.php:321)
> [stacktrace]
> #0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'array_key_exist...', 'C:\\\\xampp\\\\htdocs...', 321, Array)
> #1 C:\\xampp\\htdocs\
> eserve\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Eloquent\\Concerns\\HasAttributes.php(321): array_key_exists(Array, Array)
> #2 C:\\xampp\\htdocs\
> eserve\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Eloquent\\Model.php(1557): Illuminate\\Database\\Eloquent\\Model->getAttribute(Array)
> #3 C:\\xampp\\htdocs\
> eserve\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Eloquent\\Relations\\HasManyThrough.php(93): Illuminate\\Database\\Eloquent\\Model->offsetGet(Array)
> #4 C:\\xampp\\htdocs\
> eserve\\vendor\\staudenmeir\\eloquent-has-many-deep\\src\\HasManyDeep.php(65): Illuminate\\Database\\Eloquent\\Relations\\HasManyThrough->addConstraints()
> #5 C:\\xampp\\htdocs\
> eserve\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Eloquent\\Relations\\Relation.php(71): Staudenmeir\\EloquentHasManyDeep\\HasManyDeep->addConstraints()
> #6 C:\\xampp\\htdocs\
> eserve\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Eloquent\\Relations\\HasManyThrough.php(83): Illuminate\\Database\\Eloquent\\Relations\\Relation->__construct(Object(Illuminate\\Database\\Eloquent\\Builder), Object(App\\Models\\Reserve))
> #7 C:\\xampp\\htdocs\
> eserve\\vendor\\staudenmeir\\eloquent-has-many-deep\\src\\HasManyDeep.php(55): Illuminate\\Database\\Eloquent\\Relations\\HasManyThrough->__construct(Object(Illuminate\\Database\\Eloquent\\Builder), Object(App\\Models\\Pay), Object(App\\Models\\Reserve), 'pay_id', 'reserve_id', Array, 'id')
> #8 C:\\xampp\\htdocs\
> eserve\\vendor\\staudenmeir\\eloquent-has-many-deep\\src\\HasRelationships.php(185): Staudenmeir\\EloquentHasManyDeep\\HasManyDeep->__construct(Object(Illuminate\\Database\\Eloquent\\Builder), Object(App\\Models\\Pay), Array, Array, Array)
> #9 C:\\xampp\\htdocs\
> eserve\\vendor\\staudenmeir\\eloquent-has-many-deep\\src\\HasRelationships.php(50): App\\Models\\Pay->newHasOneDeep(Object(Illuminate\\Database\\Eloquent\\Builder), Object(App\\Models\\Pay), Array, Array, Array)
> #10 C:\\xampp\\htdocs\
> eserve\\app\\Models\\Pay.php(51): App\\Models\\Pay->hasOneDeep('App\\\\Models\\\\Serv...', Array, Array, Array)
> #11 C:\\xampp\\htdocs\
> eserve\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Eloquent\\Builder.php(586): App\\Models\\Pay->service()
> #12 C:\\xampp\\htdocs\
> eserve\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Eloquent\\Relations\\Relation.php(90): Illuminate\\Database\\Eloquent\\Builder->Illuminate\\Database\\Eloquent\\{closure}()
> #13 C:\\xampp\\htdocs\
> eserve\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Eloquent\\Builder.php(590): Illuminate\\Database\\Eloquent\\Relations\\Relation::noConstraints(Object(Closure))
> #14 C:\\xampp\\htdocs\
> eserve\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Eloquent\\Builder.php(558): Illuminate\\Database\\Eloquent\\Builder->getRelation('service')
> #15 C:\\xampp\\htdocs\
> eserve\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Eloquent\\Builder.php(538): Illuminate\\Database\\Eloquent\\Builder->eagerLoadRelation(Array, 'service', Object(Closure))
> #16 C:\\xampp\\htdocs\
> eserve\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Eloquent\\Builder.php(506): Illuminate\\Database\\Eloquent\\Builder->eagerLoadRelations(Array)
> #17 C:\\xampp\\htdocs\
> eserve\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Eloquent\\Builder.php(705): Illuminate\\Database\\Eloquent\\Builder->get(Array)
> #18 C:\\xampp\\htdocs\
> eserve\\vendor\\staudenmeir\\eloquent-has-many-deep\\src\\HasManyDeep.php(199): Illuminate\\Database\\Eloquent\\Builder->paginate(15, Array, 'page', 1)
> #19 C:\\xampp\\htdocs\
> eserve\\app\\Http\\Controllers\\User\\PayController.php(24): Staudenmeir\\EloquentHasManyDeep\\HasManyDeep->paginate()
> #20 [internal function]: App\\Http\\Controllers\\User\\PayController->index()
> #21 C:\\xampp\\htdocs\
> eserve\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Controller.php(54): call_user_func_array(Array, Array)
> #22 C:\\xampp\\htdocs\
> eserve\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('index', Array)
> #23 C:\\xampp\\htdocs\
> eserve\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Route.php(219): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(App\\Http\\Controllers\\User\\PayController), 'index')
> #24 C:\\xampp\\htdocs\
> eserve\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Route.php(176): Illuminate\\Routing\\Route->runController()
> #25 C:\\xampp\\htdocs\
> eserve\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(680): Illuminate\\Routing\\Route->run()
> #26 C:\\xampp\\htdocs\
> eserve\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(130): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
> #27 C:\\xampp\\htdocs\
> eserve\\app\\Http\\Middleware\\ActiveServiceMiddleware.php(20): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
> #28 C:\\xampp\\htdocs\
> eserve\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(171): App\\Http\\Middleware\\ActiveServiceMiddleware->handle(Object(Illuminate\\Http\\Request), Object(Closure))
> #29 C:\\xampp\\htdocs\
> eserve\\app\\Http\\Middleware\\panelShare\\UserShareMiddleware.php(24): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
> #30 C:\\xampp\\htdocs\
> eserve\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(171): App\\Http\\Middleware\\panelShare\\UserShareMiddleware->handle(Object(Illuminate\\Http\\Request), Object(Closure))
> #31 C:\\xampp\\htdocs\
> eserve\\app\\Http\\Middleware\\AllEnsureEmailIsVerified.php(48): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
> #32 C:\\xampp\\htdocs\
> eserve\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(171): App\\Http\\Middleware\\AllEnsureEmailIsVerified->handle(Object(Illuminate\\Http\\Request), Object(Closure))
> #33 C:\\xampp\\htdocs\
> eserve\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Middleware\\SubstituteBindings.php(41): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
> #34 C:\\xampp\\htdocs\
> eserve\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(171): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
> #35 C:\\xampp\\htdocs\
> eserve\\vendor\\laravel\\framework\\src\\Illuminate\\Auth\\Middleware\\Authenticate.php(43): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
> #36 C:\\xampp\\htdocs\
> eserve\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(171): Illuminate\\Auth\\Middleware\\Authenticate->handle(Object(Illuminate\\Http\\Request), Object(Closure), 'web')
> #37 C:\\xampp\\htdocs\
> eserve\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken.php(76): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
> #38 C:\\xampp\\htdocs\
> eserve\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
> #39 C:\\xampp\\htdocs\
> eserve\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Middleware\\ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
> #40 C:\\xampp\\htdocs\
> eserve\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(171): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
> #41 C:\\xampp\\htdocs\
> eserve\\vendor\\laravel\\framework\\src\\Illuminate\\Session\\Middleware\\StartSession.php(56): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
> #42 C:\\xampp\\htdocs\
> eserve\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(171): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
> #43 C:\\xampp\\htdocs\
> eserve\\vendor\\laravel\\framework\\src\\Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
> #44 C:\\xampp\\htdocs\
> eserve\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(171): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
> #45 C:\\xampp\\htdocs\
> eserve\\vendor\\laravel\\framework\\src\\Illuminate\\Cookie\\Middleware\\EncryptCookies.php(66): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
> #46 C:\\xampp\\htdocs\
> eserve\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(171): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
> #47 C:\\xampp\\htdocs\
> eserve\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
> #48 C:\\xampp\\htdocs\
> eserve\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(682): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
> #49 C:\\xampp\\htdocs\
> eserve\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(657): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
> #50 C:\\xampp\\htdocs\
> eserve\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(623): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
> #51 C:\\xampp\\htdocs\
> eserve\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(612): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
> #52 C:\\xampp\\htdocs\
> eserve\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(176): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
> #53 C:\\xampp\\htdocs\
> eserve\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(130): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
> #54 C:\\xampp\\htdocs\
> eserve\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
> #55 C:\\xampp\\htdocs\
> eserve\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
> #56 C:\\xampp\\htdocs\
> eserve\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
> #57 C:\\xampp\\htdocs\
> eserve\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
> #58 C:\\xampp\\htdocs\
> eserve\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
> #59 C:\\xampp\\htdocs\
> eserve\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
> #60 C:\\xampp\\htdocs\
> eserve\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode.php(62): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
> #61 C:\\xampp\\htdocs\
> eserve\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
> #62 C:\\xampp\\htdocs\
> eserve\\vendor\\fideloper\\proxy\\src\\TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
> #63 C:\\xampp\\htdocs\
> eserve\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(171): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
> #64 C:\\xampp\\htdocs\
> eserve\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
> #65 C:\\xampp\\htdocs\
> eserve\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
> #66 C:\\xampp\\htdocs\
> eserve\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
> #67 C:\\xampp\\htdocs\
> eserve\\public\\index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
> #68 {main}
> "} 

this my query:
`
        $pays = auth()->guard('web')->user()->pays()->with('payer','service')->latest()->paginate();
`

relation of service in pay model:
`
/**
     * relation of pay with service.
     * @return HasOneDeep
     */
    public function service()
    {
        return $this->hasOneDeep(Service::class, [Reserve::class], [null, null], [['payable_type', 'payable_id'], null]);
    }
`

thank you for answer

**Comment by staudenmeir** [comment]
Can you please post the migration/structure of all three tables?

**Comment by mohammadgh1370** [comment]
```
Schema::create('users', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->string('name');
            $table->string('family');
            $table->string('email')->unique();
            $table->string('mobile')->unique();
            $table->timestamp('email_verified_at')->nullable();
            $table->timestamp('birthday_at')->nullable();
            $table->string('password');
            $table->string('api_token')->unique()->nullable();
            $table->boolean('gender')->default(false);
            $table->string('account')->unique()->nullable();
            $table->string('web_token')->unique()->nullable();
            $table->string('app_token')->unique()->nullable();
            $table->rememberToken();
            $table->timestamps();
        });

Schema::create('services', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->text('work_time')->nullable();
            $table->text('except_day')->nullable();
            $table->string('title');
            $table->text('description')->nullable();
            $table->string('base_money');
            $table->string('duration')->nullable();
            $table->boolean('online_pay')->default(false);
            $table->unsignedBigInteger('user_id');
            $table->unsignedBigInteger('category_id');
            $table->boolean('active')->default(false);
            $table->string('phone')->nullable();
            $table->string('website')->nullable();
            $table->unsignedBigInteger('state_id')->nullable();
            $table->unsignedBigInteger('city_id')->nullable();
            $table->unsignedBigInteger('zone_id')->nullable();
            $table->text('address')->nullable();
            $table->string('lat')->nullable();
            $table->string('lng')->nullable();
            $table->string('telegram_link')->nullable();
            $table->string('instagram_link')->nullable();
            $table->timestamps();

            $table->foreign('user_id')->references('id')->on('users')
                ->onDelete('cascade')->onUpdate('cascade');
            $table->foreign('category_id')->references('id')->on('categories')
                ->onDelete('cascade')->onUpdate('cascade');
            $table->foreign('state_id')->references('id')->on('states')
                ->onDelete('cascade')->onUpdate('cascade');
            $table->foreign('city_id')->references('id')->on('cities')
                ->onDelete('cascade')->onUpdate('cascade');
            $table->foreign('zone_id')->references('id')->on('zones')
                ->onDelete('cascade')->onUpdate('cascade');
        });

public function up()
    {
        Schema::create('pays', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->morphs('payable');
            $table->morphs('payer');
            $table->string('price');
            $table->enum('type', ['place', 'online'])->default('place');
            $table->timestamp('checkout_at')->nullable();
            $table->timestamps();

            $table->index(['payable_id', 'payable_type']);
            $table->index(['payer_id', 'payer_type']);
        });
```

**Comment by staudenmeir** [comment]
It's not possible to implement a direct relationship in this case. The issue is that the path *starts* with a `MorphTo` relationship (`payable`). Due to the way relationship queries work, the `payable_type` column can't be limited to `Reserve` references.

I suggest that you use separate relationships and nested eager loading (Laravel 5.8+):

```php
class Pay extends Model
{
    public function payable()
    {
        return $this->morphTo();
    }
}

class Reserve extends Model
{
    public function service()
    {
        return $this->belongsTo(Service::class);
    }
}

$pays = auth()->guard('web')->user()->pays()->with([
    'payer',
    'payable' => function (MorphTo $payable) {
        $payable->morphWith([
            Reserve::class => ['service'],
        ]);
    },
])->latest()->paginate();
```

**Comment by mohammadgh1370** [comment]
Very, very great
Thank you so much for taking the time to answer

You are very intelligent :+1:
