### ISSUE TITLE
Morph to Many from and to Custom Pivot Model

### ISSUE THREAD

**Issue by awardx** [staudenmeir/eloquent-has-many-deep#56]
I have the following table structure

    users <-> org_members(pivot model: Member) <-> organisations -> contacts -> orders

Then there is an additional table for assigned `users` either to `contacts` or `orders` table record.

    assignables(org_member_id, assignable_id, assignable_type)

Is it possible to create the following combination both ways?

`pivot model: Member` -> morph to many -> `Contact`

I know it is easy to create relations inside `Member` model to get all assigned `Contacts` for the member even with native Laravel functionality like so

    public function assignedContacts() 
    {
           return $this->morphedByMany('App\Contact', 'assignable', null, 'org_member_id');
    }

But how to get back from `Contact` model to fetch all members that are assigned to the contact? Is it possible with hasManyDeep package?

**Comment by staudenmeir** [comment]
It's possible with an `Assignable` pivot model and a table alias:

```php
class Assignable extends MorphPivot
{
    use \Staudenmeir\EloquentHasManyDeep\HasTableAlias;

    protected $table = 'assignables';
}

class Member extends Pivot
{
    use \Staudenmeir\EloquentHasManyDeep\HasRelationships;

    protected $table = 'org_members';

    public function members()
    {
        return $this->hasManyDeep(
            self::class,
            [Assignable::class, Contact::class, Assignable::class.' as alias'],
            ['org_member_id', null, ['assignable_type', 'assignable_id'], 'id'],
            ['id', ['assignable_type', 'assignable_id'], null, 'org_member_id']
        );
    }
}

```

**Comment by awardx** [comment]
Thank you so much
