### ISSUE TITLE
Assistance with inverse of belongsToMany through hasMany

### ISSUE THREAD

**Issue by TheFrankman** [staudenmeir/eloquent-has-many-deep#57]
Hello There,

I'm using your repo to get a relationship, and i'm really struggling using it for the inverse, wondering if you could provide some assistance.

I've attached an image that explains it best. Top digram is the one that's working, bottom is the one i'm yet to figure out 

![image](https://user-images.githubusercontent.com/1402017/72603703-6f22cb80-3911-11ea-86fb-47ec8fc713b2.png)

To elaborate further this is storage -> playlist which is working (thanks!)

```
public function playlists(): HasManyDeep
{
    return $this->hasManyDeep(Playlist::class, [Item::class, 'item_playlist']);
}
```

The above works because storage HasMany items and Items BelongToMany playlists.

The inverse : as playlist belongsToMany items and an item BelongsTo storage.

So I believe what i'm looking for is BelongsTo through belongsToMany ?

**Comment by staudenmeir** [comment]
Can you post the working relationship?

**Comment by staudenmeir** [comment]
Use this:

```php
class Playlist extends Model
{
    use \Staudenmeir\EloquentHasManyDeep\HasRelationships;

    public function storages(): HasManyDeep
    {
        return $this->hasManyDeep(
            Storage::class,
            ['item_playlist', Item::class],
            [null, null, 'id'],
            [null, null, 'storage_id']
        );
    }
}
```

**Comment by TheFrankman** [comment]
You sir, are a fantastic human! Works perfectly. 

Firstly, thank you for the package.
Secondly, thank you for your quick reply!
