### ISSUE TITLE
Trait 'Staudenmeir\EloquentHasManyDeep\HasRelationships' not found

### ISSUE THREAD

**Issue by nicadeddu** [staudenmeir/eloquent-has-many-deep#6]
Hi,
i have the problem in object.
How can i solve it?
This is my code:

class Product extends Model {

    use \Staudenmeir\EloquentHasManyDeep\HasRelationships;

.....

**Comment by staudenmeir** [comment]
Has the package installation been successful? Can you see it in the output of `composer show`?
