### ISSUE TITLE
How can I detect the type of relationship with parent?

### ISSUE THREAD

**Issue by mjza** [staudenmeir/eloquent-has-many-deep#60]
As you mentioned we can:

> You can include BelongsTo relationships in the intermediate path:
> Tag → morphed by many → Post → belongs to → User

Now assume I have some relation like the above sample. Now the question is how can I detect the type of relationship between two parents in the chain, I mean with what function I can detect that relationship between Post and User is of type belongs to?

**Comment by staudenmeir** [comment]
What do you mean by "detect"? Are you asking about how to _define_ the relationship or how to _use_ it?

**Comment by mjza** [comment]
I man in the use time. I am using your library beside of [Bruno library.](https://github.com/esbenp/bruno) I use the relationship for creating joins. If I could get the type of relationship in the run time, it can help me to create the right joins.

**Comment by staudenmeir** [comment]
There is no method that returns the relationship type.

Instead, you would need to determine the type from the foreign and local keys. You can get them with `$relation->getForeignKeys()` and `$relation->getLocalKeys()`.
