### ISSUE TITLE
Is there any way using complex model scopes with hasManyDeepFromRelation?

### ISSUE THREAD

**Issue by rela589n** [staudenmeir/eloquent-has-many-deep#62]
I've tried to use hasManyDeepFromRelation in conjunction with model scopes. But combining of them is not working in the right way.
### This is what my relations looks like:

- `Test` has many `TestComposite` belongs to `Test` (many to many on self model - one test may include many other tests)
- `Test` has many `Question` (nativeQuestions)

What I need is to write `Test::allQuestions()` method.
It looks like this:
```
public function allQuestions()
{
        return $this->hasManyDeepFromRelations($this->testComposites(), (new TestComposite)->questions());
}
```
To get all `TestComposite` instances I use method:
```

public function testComposites()
{
    return $this->hasMany(TestComposite::class, 'id_test');
}
```
`TestComposite::questions` is used to get all questions of the test from right side:
```
public function questions()
{
    return $this->hasManyDeepFromRelations(
        $this->includeTest(),
        (new Test)->nativeQuestions()
    )->random($this->questions_quantity);
}
```

Get the `Test` from the right side (`TestComposite::includeTest`):
```
public function includeTest()
{
    return $this->belongsTo(Test::class, 'id_include_test');
}
```

And finally scope to get N random questions (`Question::scopeRandom`):
```
public function scopeRandom($query, $limit)
{
    return $query->inRandomOrder()->limit($limit);
}
```

### So, when I call TestComposite::questions everything works just fine, and generated sql is right:
```
select `questions`.*, `tests`.`id` as `laravel_through_key` from `questions` inner join `tests` on 
`tests`.`id` = `questions`.`test_id` where `tests`.`deleted_at` is null and `tests`.`id` = 11 and 
`questions`.`deleted_at` is null order by RAND() limit 2
```
### But, as soon as I want call Test::allQuestions it gives me the unexpected sql shown below (I expected the unions of above sql):
```
select `questions`.*, `test_composite`.`id_test` as `laravel_through_key` from `questions` inner join 
`tests` on `tests`.`id` = `questions`.`test_id` inner join `test_composite` on 
`test_composite`.`id_include_test` = `tests`.`id` where `tests`.`deleted_at` is null and 
`test_composite`.`id_test` = 16 and `questions`.`deleted_at` is null
```

###  I would appreciate any help. If there is some workaround, please let me know.

**Comment by staudenmeir** [comment]
I'll look into it.

**Comment by staudenmeir** [comment]
It's not explicitly stated in the documentation, but `hasManyDeepFromRelations()` doesn't apply additional constraints from the original relationships.

You'll also need to apply the `random` scope to the `allQuestions` relationship.

**Comment by rela589n** [comment]
It is impossible, because questions_quantity is property of intermediate model...

**Comment by staudenmeir** [comment]
The scope can't actually work/doesn't make sense for the `allQuestions` relationship: 
With `questions_quantity` being an attribute of an intermediate model, every `Test` query would have multiple (different) limits.

**Comment by rela589n** [comment]
The thing is that Test may include questions from another Tests. Let's assume we have `Test A` (30 native questions), `Test B` (20 native questions) and `Test C` (10 native questions). But the teacher want `Test C` to include 15 native questions from `Test B` and 10 questions from `Test A`. The `allQuestions` should return query that get 10 questions from A, 15 from B and 10 of C. The `test_compostite` table is intermediate and contain `id_test` (id of original test), `id_include_test` (id of test to include) and `questions_quantity` (limit questions to include).

**Comment by staudenmeir** [comment]
If you provide a database dump with the tables and some sample data, I'll have a look.

**Comment by rela589n** [comment]
### What my tables look like:
![firefox_h7dfXyewVM](https://user-images.githubusercontent.com/41589422/75116286-5ecbe200-566f-11ea-8f7d-e74de4ec0d96.png)
### Sample database dump: [dump](https://anonfile.com/5audy0cbo3/sample_sql)

**Comment by staudenmeir** [comment]
I don't see a way to implement this as a single query, let alone a relationship.

**Comment by rela589n** [comment]
### What about simple unions?
#### For example:
```
(select `questions`.*, `tests`.`id` as `laravel_through_key` from `questions` inner join `tests` on `tests`.`id` = `questions`.`test_id` where `tests`.`deleted_at` is null and `tests`.`id` = 2 and `questions`.`deleted_at` is null order by RAND() limit 5)
union
(select `questions`.*, `tests`.`id` as `laravel_through_key` from `questions` inner join `tests` on `tests`.`id` = `questions`.`test_id` where `tests`.`deleted_at` is null and `tests`.`id` = 4 and `questions`.`deleted_at` is null order by RAND() limit 999)
```

**Comment by staudenmeir** [comment]
Yes, but you need an additional query to get the test IDs. That's what makes this so complex.

**Comment by rela589n** [comment]
Could you look into it please? 
SQL function [group_concat](https://stackoverflow.com/questions/2129693/using-limit-within-group-by-to-get-n-results-per-group#answer-15585351)

**Comment by rela589n** [comment]
What workaround would you suggest for this situation? (If I want return builder from my method)

**Comment by staudenmeir** [comment]
You would need to get all included tests through `test_composite` and then build the UNION query dynamically with one subquery for the parent test and one subquery for each related test.
