### ISSUE TITLE
Has Many Deep with Limit/Take not working in L6

### ISSUE THREAD

**Issue by fmcdigital** [staudenmeir/eloquent-has-many-deep#64]
Versions:

- Laravel 6.17.1
- "staudenmeir/eloquent-eager-limit": "^1.0",
- "staudenmeir/eloquent-has-many-deep": "^1.11",

I got the following error:

```
BadMethodCallException
Method Illuminate\Database\Query\Grammars\MySqlGrammar::useLegacyGroupLimit does not exist.

http://localhost:3000/admin/api/requests/apartments/13?offset=1&qty=100

Bad Method Call
Did you mean Illuminate\Database\Query\Grammars\MySqlGrammar::compileLimit() ?
```

I installed `staudenmeir/eloquent-eager-limit` and got the error.

**Comment by fmcdigital** [comment]
I deleted the folder `staudenmier` from my project using Laravel 5.7 and it worked on the 6.0.
Strange, that it uses this package version 1.7 without the need of installing `Eager Limit Package`. But when I tried to install the `1.7` via composer it gave an error.

**Comment by staudenmeir** [comment]
What versions of my packages does Composer install?

Are you using the `HasEagerLimit` trait in both models?

**Comment by parelius** [comment]
I have a similar issue:

Using 

- php 7.4.2
- mysql 5.7.28
- laravel/framework 7.6.1
- staudenmeir/eloquent-has-many-deep 1.12

I got the message:
>Please install staudenmeir/eloquent-eager-limit to limit eager loading queries.

thrown by Staudenmeir\EloquentHasManyDeep\HasEagerLimit.php(33).

After installing 

- staudenmeir/eloquent-eager-limit 1.5

I get the error:

> Method Illuminate\Database\Query\Grammars\MySqlGrammar::useLegacyGroupLimit does not exist.

Indeed, I can't find any useLegacyGroupLimit method in `Illuminate\Database\Query\Grammars\MySqlGrammar`.

I don not use the `HasEagerLimit` trait in my code.
Any idea how to fix this? Thanks in advance.

**Comment by staudenmeir** [comment]
@parelius You need to use the `HasEagerLimit` trait in both the parent and the related model:
https://github.com/staudenmeir/eloquent-eager-limit#usage

**Comment by parelius** [comment]
Well, I'm using `staudenmeir/eloquent-eager-limit` because `staudenmeir/eloquent-has-many-deep` cries for it.
Therefore I didn't use the `HasEagerLimit`trait in my models.

Adding this trait does not change anything.

What about the `Illuminate\Database\Query\Grammars\MySqlGrammar`?

I should mention that the problem does not occur in local development, but on the staging and production server only.

**Comment by staudenmeir** [comment]
@parelius Please verify that both models are also using the trait in your staging and production environments. The error message strongly indicates that they aren't.

**Comment by problem9** [comment]
for any one wondering what is the problem, for me solution was to use RIGHT HasEagerLimit trait,

if you use HasEagerLimit trait from staudenmeir/eloquent-has-many-deep, it will not work, but if you use from staudenmeir/eloquent-eager-limit, it all starts working. but i don't know why they are two version or why the one with package is broken.
