### ISSUE TITLE
doesn't work together jsonRelation

### ISSUE THREAD

**Issue by BUGOVER** [staudenmeir/eloquent-has-many-deep#67]
`$this->hasManyDeepFromRelations($this->cities(), (new City())->franchisees());
`

City
`
    public function franchisees(): HasManyJson
    {
        return $this->hasManyJson(FranchiseRegion::class, 'city->ids', 'city_id');
    }`

**Comment by staudenmeir** [comment]
I just released new versions for both packages that add support for relationships like yours (Laravel 9+).
