### ISSUE TITLE
foreign and local keys and for hasMany to belongsToMany relation

### ISSUE THREAD

**Issue by nitish1986** [staudenmeir/eloquent-has-many-deep#69]
Hi,

I'm trying to establish a relation between models as `Role`  ---> `hasMany` ---> `Award` ---> `belongsToMany` ---> `Company`

My `Role` model looks something like:

    public function awards()
    {
        return $this->hasMany(Award::class, 'awardee_role', 'id');
    }

My `Award` models looks like:

    public function awardedBy()
    {
        return $this->belongsToMany(Company::class, 'award_awarded_relation', 'award_id', 'company_id');
    }

I'm trying to establish the relationship in `Role` model something like this:

    public function companies()
    {
        return $this->hasManyDeep(Company::class, [Awards::class, 'award_awarded_relation'])
    }

Obviously it is trying to find role_id in my awards table, so I wanted to override the default functionality. I'm bit confused and not able to achieve this somehow, help me out with it.

Thanks

**Comment by staudenmeir** [comment]
Specify the custom foreign key in the third argument:

```php
public function companies()
{
    return $this->hasManyDeep(
        Company::class,
        [Awards::class, 'award_awarded_relation'],
        ['awardee_role']
    )
}
```
