### ISSUE TITLE
Support for ManyToMany?

### ISSUE THREAD

**Issue by NicksonYap** [staudenmeir/eloquent-has-many-deep#7]
Given the relationship:
`Country` → has many to many → `User `→ has many to many → `Post`

Can we get: all `Posts` of all `Users` in a `Country`

**Comment by staudenmeir** [comment]
Take a look at the documentation:
https://github.com/staudenmeir/eloquent-has-many-deep#belongstomany

**Comment by NicksonYap** [comment]
@staudenmeir Thanks!

However, I'm using belongsToMany then belongsToMany again (two pivot tables)
Plus I had to input my foreign and local keys
so it got really confusing

It took me a while to understand the pattern but got it to work, I'm so happy!

Below's an example code, untested with the exact Model & Pivot Tables but should work 
(if I mapped the keys and tables correctly)


Example:
`User` → belongs to many → `Role` → belongs to many → `Permission`

```php
class User extends Model
{
    use \Staudenmeir\EloquentHasManyDeep\HasRelationships;

    public function permissions()
    {
        return $this->hasManyDeep(
            'App\Permission',
            ['role_user', 'permission_role'], // Intermediate models and tables, beginning at the far parent (User).
            [           
               'user_id', // Foreign key on the "role_user" table.
               'permission_id',      // Foreign key on the "permission_role" table
               'id'  // Foreign key on the "permissions" table. (local key)
            ],
            [          
              'id',         // Local key on the "users" table.
              'role_id', // Local key on the "role_user" table (foreign key).
              'role_id   // Local key on the "permission_role" table.
            ]
        );
    }
}
```

**Comment by NicksonYap** [comment]
@staudenmeir 

Honestly, this should be integrated into Laravel, consider submitting a PR? :)

It took me two days, trying all sorts of ways.
as I've searched for a lot of outdated solutions
(this seems like an issue ever since Laravel was out in 2014)

----

Note:

I think the readme should be updated with some mentions of the keyword:
HasManyThrough and  Many-To-Many
For it to be more SEO friendly (I only found this repo is some 2014 thread in Laravel.io)

**Comment by staudenmeir** [comment]
You don't have to specify the keys when you add the `Role` model between the pivot tables:

```php
class User extends Model
{
    use \Staudenmeir\EloquentHasManyDeep\HasRelationships;

    public function permissions()
    {
        return $this->hasManyDeep(
            'App\Permission',
            ['role_user', 'App\Role', 'permission_role']
        );
    }
}
```

**Comment by NicksonYap** [comment]
@staudenmeir 

But the keys used in my table is not the same as the model name
Do u mean that by putting 'App\Role',  in between 'role_user' and 'permission_role'
Would eliminate the need for the key names to be defined?

**Comment by NicksonYap** [comment]
Thanks!

No doubt it will work if the column naming is according to the model name,

but the names of my keys are not following the model name so i Have to do it the manual way like in previous comment: https://github.com/staudenmeir/eloquent-has-many-deep/issues/7#issuecomment-431477943
