### ISSUE TITLE
HasMany → ManyToMany

### ISSUE THREAD

**Issue by osqui** [staudenmeir/eloquent-has-many-deep#73]
Is it possible to perform this action?

**Comment by staudenmeir** [comment]
Yes, take a look at the example:
https://github.com/staudenmeir/eloquent-has-many-deep#manytomany--hasmany

**Comment by osqui** [comment]
Hi Jonas,

Thanks for your quick response.

I have read your packege's documentation, but I can't figure out how to
perform this action:

I have a *projects* table.
I have a *tasks* table, with a *project_id* column, so I'm using HasMany.
I have a *task_user* table, so I'm using BelongsToMany (task_id, user_id).
This table doesn't have a project_id key.
I need to get all the users that belong to a project throught the tasks.

Thanks again, and of course thanks for your great package!

**Comment by staudenmeir** [comment]
Use this relationship:

```php
class Project extends Model
{
    use \Staudenmeir\EloquentHasManyDeep\HasRelationships;

    public function users()
    {
        return $this->hasManyDeep(User::class, [Task::class, 'task_user']);
    }
}
```

**Comment by osqui** [comment]
It works, thank you so much :)
