### ISSUE TITLE
Is it correct to get the results ungrouped?

### ISSUE THREAD

**Issue by tsekka** [staudenmeir/eloquent-has-many-deep#74]
Hi

Is it correct that I'm getting the results ungrouped eg. considering the example
 
`Users -> Roles -> Permissions`,

when User has 2 roles: "editor" and "subscriber",

both having permission "read", 

then user->permissions will return the same permission "read" 2 times?

Useful package even if I'd have to do grouping manually, but was just wondering if I'm missing something.

Thanks.

**Comment by staudenmeir** [comment]
Yes, that's the correct behavior.
