### ISSUE TITLE
[Question] about "account has many roles has many permissions"

### ISSUE THREAD

**Issue by eyemovic-oie** [staudenmeir/eloquent-has-many-deep#76]
This is my first time using this library.
I read the documentation, but I didn't understand.
(I'm inexperienced...)

### Question

Is there a way to get a list of permissions from the account model in the following cases?
User A can read and write.

### My tables

**accounts**
|account_id (primary key)|name|
|---|---|
|1|User A|
|2|User B|

**model_has_roles**
|role_id|model_type|model_id|
|---|---|---|
|1|App\Http\Models\Account|1|

**roles**
|id|name|
|---|---|
|1|super_user|
|2|normal_user|

**permissions**
|id|name|
|---|---|
|1|read|
|2|write|

**permission_role**
|permission_id|role_id|
|---|---|
|1|1|
|2|1|
|1|2|

**Comment by staudenmeir** [comment]
Use this relationship:

```php
class Account extends Model
{
    use \Staudenmeir\EloquentHasManyDeep\HasRelationships;

    public function permissions()
    {
        return $this->hasManyDeep(
            Permission::class,
            ['model_has_roles', Role::class, 'permission_role'],
            [['model_type', 'model_id'], 'id'],
            [null, 'role_id']
        );
    }
}
```

**Comment by eyemovic-oie** [comment]
@staudenmeir 
Resolved.

I really appreciate it.
Thank you!
