### ISSUE TITLE
Is it possible to define a many to many - belongsto relation?

### ISSUE THREAD

**Issue by SuperDJ** [staudenmeir/eloquent-has-many-deep#78]
Having the following tables:

projects | _
--- | ---
id | name

bundle_participant_project | _ | _
--- | --- | ---
id | bundle_participant_id | project_id

bundle_participant | _ | _
--- | --- | ---
id | bundle_id | participant_id

bundles | _ | _
--- | --- | ---
id | name 

I would like to have a relationship between project and bundels. So is it possible to make a `projects` many to many `bundle_participant` belongs to `bundles` relationship?

**Comment by staudenmeir** [comment]
Use this relationship:

```php
class Project extends Model
{
    use \Staudenmeir\EloquentHasManyDeep\HasRelationships;

    public function bundles()
    {
        return $this->hasManyDeep(
            Bundle::class,
            ['bundle_participant_project', BundleParticipant::class],
            [null, null, 'id'],
            [null, null, 'bundle_id']
        );
    }
}
```

**Comment by SuperDJ** [comment]
Had to add set `bundle_participant_id` as well or it would be set to nothing returning an error.

```php
return $this->hasManyDeep(
    Bundle::class,
    ['bundle_participant_project', BundleParticipant::class],
    [null, null, 'id'],
    [null, 'bundle_participant_id', 'bundle_id']
);
```

**Comment by MrEduar** [comment]
Hello, I have exactly the same relationship in my database.
The problem is that using it this way brings me as many bundles as `bundle_participant` exists.

In my case they are not `bundles`.
In my case I have 
`Genre `→ many to many → `Song `→ belongs to → `Album`

Then I have my relationship as

```
class Genre extends Model
{
    use HasRelationships;

    public function albums()
    {
        return $this->hasManyDeep(
            Album::class,
            ['genre_song', Song::class],
            [null, null, 'id'],
            [null, null, 'album_id']
        );
    }
}
```
And it works, but as I said at the beginning it brings me all 10 repeat albums if the album has 10 songs... Any help with this?

**Comment by staudenmeir** [comment]
@MrEduar Yes, you can use `distinct()`.
