### ISSUE TITLE
Does not work with multiple databse connections.

### ISSUE THREAD

**Issue by buglinjo** [staudenmeir/eloquent-has-many-deep#79]
The model I'm trying to get has a different connection than the model I'm referring from.  
Please add functionality which will enable us to select connection per model in the array.

```php
return $this
	->setConnection('con1')
	->hasManyDeep(
	Model1::class,
	[
		DB::connection('con1')->getDatabaseName() . '.pivot_table',
		<DB connection 'con1'> ... Model2::class,
	]
);
```

**Comment by staudenmeir** [comment]
Please provide your actual relationship with the database connection of each model.

**Comment by buglinjo** [comment]
Figured it out with setting table name inside the model.

```php
public function __construct(array $attributes = [])
{
	parent::__construct($attributes);

	$this->table = DB::connection($this->getConnectionName())->getDatabaseName() . '.' . $this->getTable();
}
```

Thank you! Great package!
