### ISSUE TITLE
Possible to merge two Relations?

### ISSUE THREAD

**Issue by NicksonYap** [staudenmeir/eloquent-has-many-deep#8]
Hi

I've successfully implemented this Laravel package, it's awesome

I have two possible Relations:

```
Order -> belongs to many -> DeliveryOrder -> belongs to many -> Invoices
```

```
Order -> belongs to many -> Invoices
```

Some `Orders` can relate directly to `Invoices`, some will have to go through `DeliveryOrder`

They have different possible paths but the start and end Models of the possible paths are the same

I'm able to use hasManyDeep to get both relations, separately

But how can we add support or workaround to combine the two Relations into one?

(not asking to convert into a Collection or array and merge them, that's cheating)

Thanks!

**Comment by staudenmeir** [comment]
Should the merged relationship be a "real" relationship (with support for eager loading etc.)? Or do you just want to get the invoices from both sources in a single query?

**Comment by NicksonYap** [comment]
Real relationship with eager loading 😅

**Comment by staudenmeir** [comment]
I don't see a (feasible) way to do this.

**Comment by staudenmeir** [comment]
I don't think it's that simple. The only way I see is a `UNION` query.

**Comment by NicksonYap** [comment]
@staudenmeir 

I've managed to `union()` two `manyToMany` & `hasManyDeep` relations, however there were a number of workarounds required.

one would normally do this: (the following does not work)

```php
public function combined_relations(){
  return $this->firstRelation()->union($this->secondRelation());
}
```

However because Laravel has issues applying union to manyToMany relationships, this has to be done:

```php
public function combined_relations(){
  //fix due to extra columns from pivot tables
  return $this->firstRelation()->select('table_name.*')->union($this->secondRelation()->select('table_name.*'));
}
```

But it returns a `Builder` instance, not a `Relations` instance like `belongsToMany()` or `hasMany()`

So it does not work with `whereHas()` or `with()`

Do you know how to convert a `Builder` instance into a `Relations` instance?

I managed to get an array and `hydrate()` it back into Eloquent/Model

**Comment by staudenmeir** [comment]
Can you post the view solution?

**Comment by staudenmeir** [comment]
I've created a package for merging relationships using views:
https://github.com/staudenmeir/laravel-merged-relations

First, create the merge view in a migration:

```php
use Staudenmeir\LaravelMergedRelations\Facades\Schema;

Schema::createMergeView(
    'all_invoices', [(new Order)->invoices(), (new Order)->deliveryInvoices()]
);
````

If you want to get unique results:

```php
use Staudenmeir\LaravelMergedRelations\Facades\Schema;

Schema::createMergeViewWithoutDuplicates(
    'all_invoices', [(new Order)->invoices(), (new Order)->deliveryInvoices()]
);
````

Then define the relationship:

```php
class Order extends Model
{
    use \Staudenmeir\LaravelMergedRelations\Eloquent\HasMergedRelationships;

    public function allInvoices()
    {
        return $this->mergedRelationWithModel(Invoice::class, 'all_invoices');
    }

    public function invoices()
    {
        return $this->belongsToMany(Invoice::class);
    }

    public function deliveryInvoices()
    {
        return $this->hasManyDeep(
            Invoice::class,
            ['delivery_order_order', DeliveryOrder::class, 'delivery_order_invoice']
        );
    }
}

Order::find($id)->allInvoices;

Order::with('allInvoices')->get();
````

**Comment by androidhands** [comment]
@staudenmeir I have used your package and when run migration I get this error.   Call to undefined method Staudenmeir\LaravelMergedRelations\Facades\Schema::createMergeView() . Please can you help me.

**Comment by staudenmeir** [comment]
@androidhands Please create a new issue:
https://github.com/staudenmeir/laravel-merged-relations/issues/new
