### ISSUE TITLE
HasOneDeep requires staudenmeir/eloquent-eager-limit 

### ISSUE THREAD

**Issue by ChristopheB** [staudenmeir/eloquent-has-many-deep#82]
I have a _HasOneDeep_ relationship, and [it tells me](https://github.com/staudenmeir/eloquent-has-many-deep/blob/master/src/HasEagerLimit.php#L33):

> Please install staudenmeir/eloquent-eager-limit to limit eager loading queries.

That begs me a question: does _HasOneDeep_ really require the `eloquent-eager-limit` package?
As far as I know, the addition of [HasOneDeep](https://github.com/staudenmeir/eloquent-has-many-deep/commit/b188e07c9034865a605d9ed1790507c49ae202a4) is older than the [eager loading with limit ](https://github.com/staudenmeir/eloquent-has-many-deep/commit/461962be960839d3d4bd121496a706ca7d990a7e)feature.

It's not that I don't want to use the `eloquent-eager-limit` package, but using it complexifies the code I'm currently working on quite a bit, as it conflicts with [another package](https://github.com/topclaudy/compoships) I'm using.

I'll be glad to write a PR if needed, but I don't really know what would be the best way to bypass the package for hasOneDeep.

**Comment by staudenmeir** [comment]
You are receiving this message because you are applying `limit()`/`take()` to the relationship. Laravel has no native support for limiting eager loading results, that's why the package is necessary.

You should be able to resolve the conflict with https://github.com/mpyw/compoships-eager-limit.

**Comment by ChristopheB** [comment]
Many thanks for the link on compoships-eager-limit!

The thing is that I don't apply anything to the relationship, I just try to load it like so `$model->relation`.

But I finally managed to isolate my issue: the relationship is loaded against a new unsaved model and [this code](https://github.com/staudenmeir/eloquent-has-many-deep/blob/master/src/HasEagerLimit.php#L29) was kicking me out.

It's working fine with `if ($this->farParent)` instead of `if ($this->farParent->exists)`, but not sure if that makes sense overall.

**Comment by staudenmeir** [comment]
How is your relationship defined?

**Comment by ChristopheB** [comment]
Here is below a simplified version, not sure if that can help.

An order has a _vendor_reference_ text attribute, and we try to find out if a contract exists that is bound to a known list of vendor references. The deep relation comes in because one vendor reference may have several aliases.

```php
<?php

class Order
{
    public function contractsFromVendorReference()
    {
        return $this->hasOneThrough(Contract::class, VendorReference::class, 'value', 'vendor_reference_id', 'vendor_reference', 'id');
    }

    public function contractsFromVendorReferenceAlias()
    {
        return $this->hasOneDeep(
                Contract::class, [VendorReferenceAlias::class, VendorReference::class],
                ['value', 'id', 'vendor_reference_id'], ['vendor_reference', 'vendor_reference_id', 'id']
            );
    }
}
```

| orders | contracts | vendor_references | vendor_reference_aliases
| ------------- | ------------- | ------------- | ------------- |
| vendor_reference | vendor_reference_id  | value | vendor_reference_id
| ... | ... | | value

**Comment by staudenmeir** [comment]
How are you using the relationship? Are you retrieving the contract with `->first()`?

**Comment by ChristopheB** [comment]
Yes sorry, forgot that part. This code hits [the exists](https://github.com/staudenmeir/eloquent-has-many-deep/blob/master/src/HasEagerLimit.php#L29) check:
```php
$order = new Order(['vendor_reference' => '123'];
$order->contractsFromVendorReferenceAlias;
```

**Comment by ChristopheB** [comment]
Not sure if that particular case would need a deep dive and a fix honestly. I can get around it in several ways, including the compoships-eager-limit you mentioned.

Feel free to close the issue!

**Comment by staudenmeir** [comment]
Ok, this is the issue: The limit is applied when you [retrieve](https://github.com/laravel/framework/blob/de4c42f04d609b119a4e0a7e6223c37bfe54cb87/src/Illuminate/Database/Eloquent/Relations/HasManyThrough.php#L286) the contract. The package thinks you are using eager loading because it can't really differentiate that from lazy loading on an unsaved model.

In your case, you could also apply `first()` directly to the query builder:

```php
$order->contractsFromVendorReferenceAlias()->getQuery()->first();
```

**Comment by ChristopheB** [comment]
Nice workaround!

Thank you very much for the explanation and for your time, this definitely correlates with the stack trace I have but didn't fully understand.

**Comment by ChristopheB** [comment]
With the call on the query builder, it actually messes up the contract id in the result (the vendor reference alias id is bound to `$contract->id`)

```php
$contract = $order->contractFromVendorReferenceAlias()->getQuery()->first();
// => $contract->id is wrong
```

So I ended up calling the full result set like so:
```php
$contract = $order->contractFromVendorReferenceAlias()->get()->first();
// => $contract->id is OK
```
