### ISSUE TITLE
Why does hasOneDeepFromRelations return a collection?

### ISSUE THREAD

**Issue by kevinruscoe** [staudenmeir/eloquent-has-many-deep#84]
I'm in a situation where hasOneDeepFromRelations returns a collection of the same model. I can see why this but shouldn't a "hasOne" imply 1 model will be returned?

**Comment by staudenmeir** [comment]
How is the relationship defined and how are you using it?

**Comment by kevinruscoe** [comment]
It's a bit of a complicated one. 

- A Product hasMany ProductOptions (such as Size, Colour, etc)
- An Option hasMany ProductOptionValues (such as Red, Blue, etc)
- A ProductVariant belongsToMany ProductOptionValues (such as Red, Small)

This works fine. Now, I'm trying to trace the parent Product from the ProductVariant (through the pivot table `product_variant_product_option_value`, then ProductOptionValue -> ProductOption -> Product).

```
public function product() : Relation
    {
        return $this->hasOneDeepFromRelations(
            $this->optionValues(),
            (new ProductOptionValue)->option(),
            (new ProductOption())->product()
        );
        // TODO: For some reason this returns a collection? Not a single model.
        // Until this is fixed, the magic `->product` is manually getting the model
        // @link https://github.com/staudenmeir/eloquent-has-many-deep/issues/84
    }

    /**
     * The option values, such as: red, small, etc.
     *
     * @return Relation
     */
    public function optionValues() : Relation
    {
        return $this->belongsToMany(ProductOptionValue::class);
    }

    /**
     * The options, such as: colour, size, etc.
     *
     * @return Relation
     */
    public function options() : Relation
    {
        return $this->hasManyDeepFromRelations(
            $this->optionValues(),
            (new ProductOptionValue)->option()
        );
    }
```

The hasOneDeepFromRelations() relatinship returns a collection, which makes sense. The ProductOptionValue would contain multi products, depite them actually being the same model. But shouldn't has one, just return 1 product? Not a collection?

**Comment by staudenmeir** [comment]
How are you using the `product` relationship?

**Comment by kevinruscoe** [comment]
Apparently incorrectly! 

Calling `$this->product()->get()` return a collection, but letting laravel do it's magic with just `$this->product` seems to work. Thank for letting me talk through my problem :)
