### ISSUE TITLE
Support for laravel ide-helper

### ISSUE THREAD

**Issue by efinder2** [staudenmeir/eloquent-has-many-deep#86]
Thank you for this great library in advance. This library would be even better if it supported the [laravel/lumen ide-helper](https://github.com/barryvdh/laravel-ide-helper). It breaks the workflow to create the php-doc for the hasManyDeepFromRelations relations by hand. It would be much easier if they were automatically generated.

**Comment by staudenmeir** [comment]
How do you mean? What would I need to do to support the IDE helper?

**Comment by efinder2** [comment]
I've digged into their code. Is not possible to extend the list of supported relation types. This is currently a hard coded mapping array from return type class name to relation.

In two weeks I have some free days. Then I'll create a pull request on their end to make it possible to extend this array by the new relation types. I'll reopen this when done.

**Comment by efinder2** [comment]
The pull request under development: https://github.com/barryvdh/laravel-ide-helper/pull/987
