### ISSUE TITLE
[BUG] hasManyDeepFromRelations doesnt respect the relation constraints

### ISSUE THREAD

**Issue by ctf0** [staudenmeir/eloquent-has-many-deep#91]
consider the following relations
``` php
// User Model
public function accounts()
{
    return $this->hasMany(Account::class);
}

public function avail_accounts()
{
    return $this->accounts()->isActive();
}

public function regions()
{
    return $this->hasManyDeepFromRelations($this->accounts(), (new Account())->region())
        ->distinct()
        ->orderBy('name');
}

public function avail_regions()
{
    return $this->hasManyDeepFromRelations($this->avail_accounts(), (new Account())->region())
        ->distinct()
        ->orderBy('name');
}

// Account Model
public function region()
{
    return $this->belongsTo(Region::class);
}
```

when using any of `regions` or `avail_regions`, they will return the same result.
however when trying `accounts.region` & `avail_accounts.region` on their own, they works correctly.

if u need more info, plz ask.

**Comment by staudenmeir** [comment]
Please see #36.

**Comment by ctf0** [comment]
isn't there away around it to make sure the relation constraint is applied ? even an unreleased solution ?

**Comment by ctf0** [comment]
> Why wouldn't this work here?

because `->isActive()` is actually a `whereHas` not a boolean scope & writing it manually like

```
public function avail_regions()
{
    return $this->hasManyDeepFromRelations($this->accounts(), (new Account())->region())
        ->whereHas('accounts', function($q) {
              $q->isActive();
        })
        ->distinct()
        ->orderBy('name');
}
```

gives error that the relation is not found

**Comment by staudenmeir** [comment]
I see. I'll think about a workaround.

**Comment by staudenmeir** [comment]
How is the `isActive()` scope defined?

**Comment by ctf0** [comment]
```
->whereHas('accounts', function($q) {
      $q->where('is_active', true);
})
```

not sure if this will help or not, but sometimes the `whereHas` could also have a nested `whereHas`.

**Comment by staudenmeir** [comment]
The `Account` model itself has an `accounts` relationship?

**Comment by ctf0** [comment]
u mean like a parent-child relation ? if yes the noit doesnt.

**Comment by staudenmeir** [comment]
> ->whereHas('accounts', function($q) {
>       $q->where('is_active', true);
> })

In which model is this `isActive()` scope defined?

I was referring to the scope that you are using here:

```php
public function avail_accounts()
{
    return $this->accounts()->isActive();
}
```

**Comment by ctf0** [comment]
ah yes, on the `Account` model

**Comment by staudenmeir** [comment]
Please share the whole `Account` model.

**Comment by ctf0** [comment]
> The Account model itself has an accounts relationship?

sorry i misunderstood.

sure
```php
<?php

namespace App\Models;

class Account extends BaseModel
{
    /* -------------------------------------------------------------------------- */
    /*                                  RELATIONS                                 */
    /* -------------------------------------------------------------------------- */

    public function region()
    {
        return $this->belongsTo(Region::class);
    }

    /* -------------------------------------------------------------------------- */
    /*                                   SCOPES                                   */
    /* -------------------------------------------------------------------------- */

    public function scopeIsActive($q)
    {
        return $q->whereHas('region', function ($t) {
            $t->isActive();
        });
    }
}
```

**Comment by staudenmeir** [comment]
How is `Region::scopeIsActive()` defined?

**Comment by ctf0** [comment]
`$q->where('is_active', true);

**Comment by staudenmeir** [comment]
You can manually add the scope's constraint and binding to the relationship:

```php
public function avail_regions()
{
    $accounts = $this->avail_accounts();

    $regions = $this->hasManyDeepFromRelations($accounts, (new Account())->region())
        ->distinct()
        ->orderBy('name');

    $regions->getBaseQuery()->wheres[] = end($accounts->getBaseQuery()->wheres);
    $regions->getBaseQuery()->bindings['where'][] = end($accounts->getBaseQuery()->bindings['where']);

    return $regions;
}
```

**Comment by ctf0** [comment]
isnt there a better way of doing this instead of manual ? specially that now we have to duplicate the code in both the original and the new one.

**Comment by staudenmeir** [comment]
There isn't.

**Comment by ctf0** [comment]
is there a blueprint/steps to follow with any case to get things to work or does each scenario has its own setup ?

**Comment by staudenmeir** [comment]
You need to take the relationship with constraints (e.g. `$this->avail_accounts()`) and add its additional constraints (from the base query) to the `hasManyDeepFromRelations()` relationship's base query. In this case, there's one constraint and one binding.

**Comment by ctf0** [comment]
great, much appreciated.

**Comment by ctf0** [comment]
one more question plz,

what if i have multiple wheres, how
```
$regions->getBaseQuery()->wheres[] = end($accounts->getBaseQuery()->wheres);
$regions->getBaseQuery()->bindings['where'][] = end($accounts->getBaseQuery()->bindings['where']);
```

would look like ?

maybe we could have a loop to search for all the constraints automatically and add them to the query ?

**Comment by staudenmeir** [comment]
Loop over the bindings separately:

```php
public function avail_regions()
{
    $accounts = $this->avail_accounts();

    $regions = $this->hasManyDeepFromRelations($accounts, (new Account())->region())
        ->distinct()
        ->orderBy('name');

    foreach ($accounts->getBaseQuery()->wheres as $item) {
        $regions->getBaseQuery()->wheres[] = $item;
    }

    foreach ($accounts->getBaseQuery()->bindings['where'] as $binding) {
        $regions->getBaseQuery()->bindings['where'][] = $binding;
    }

    return $regions;
}
```

**Comment by ctf0** [comment]
thank you so much, i was thinking of maybe turning this into a helper function so others can use it so the usage will be

```php
public function avail_regions()
{
    $relation = $this->avail_accounts();

    return $this->hasManyDeepFromRelationsWithConstrains(
        $relation,
        $this->hasManyDeepFromRelations($relation, (new Account())->region())
            ->distinct()
            ->orderBy('name')
    );
}

protected function hasManyDeepFromRelationsWithConstrains($relation, $sub_relation)
{
    // constraints
    foreach ($relation->getBaseQuery()->wheres as $item) {
        $sub_relation->getBaseQuery()->wheres[] = $item;
    }

    foreach ($relation->getBaseQuery()->bindings['where'] as $binding) {
        $sub_relation->getBaseQuery()->bindings['where'][] = $binding;
    }

    // final
    return $sub_relation;
}
```

so the original usage of `hasManyDeepFromRelations` remains the same while getting the expected query, if its okey with you i can make a PR with that.

**Comment by staudenmeir** [comment]
Thanks, but I want to release a method that also covers more complex edge cases. That's the reason I haven't released such a helper yet.

**Comment by ctf0** [comment]
ok np, btw i've also found that no constraints can be added to the sub relation as well ex.

```php
public function avail_regions()
{
    return $this->hasManyDeepFromRelations(
           $this->avail_accounts(), 
           (new Account())->region()->whereHas(....) // this wont have any effect
        )
        ->distinct()
        ->orderBy('name');
}
```

**Comment by staudenmeir** [comment]
I released `v1.15.3` with [`hasManyDeepFromRelationsWithConstraints()`](https://github.com/staudenmeir/eloquent-has-many-deep#existing-relationships-constraints):

```php
public function avail_regions()
{
    return $this->hasManyDeepFromRelationsWithConstraints([$this, 'avail_accounts'], [new Account(), 'region'])
        ->distinct()
        ->orderBy('name');
}
```

**Comment by hasnat-we** [comment]
@staudenmeir Thanks a lot for the update. Is this possible to release the constraint version for PHP 7.4 version? Thanks

**Comment by staudenmeir** [comment]
@hasnat-we What version of the package are you using?
