### ISSUE TITLE
withCount counting duplicates ?

### ISSUE THREAD

**Issue by toyi** [staudenmeir/eloquent-has-many-deep#97]
Hello,

I have a relationship structured like this:

`User` → many to many → `Role` → many to many → `Permission`

```php
public function products()
{
    return $this->hasManyDeep(Product::class, ['headlight_vehicle_variant', Headlight::class, 'headlight_product']);
}
```
So :
`Product` → many to many → `Headlight`→ many to many → `VehicleVariant`

When i fetch the results with something like that (where `110275` is just one of the many VehicleVariant, it is not relevant here):

```php
VehicleVariant::query()->with('products')->find(110275);
```

826 products are loaded.

 In reality, there is only 567 unique products. I'm still investigating why, but the point is, if i add `->distinct()` to the relationship:

```php
public function products()
{
    return $this->hasManyDeep(Product::class, ['headlight_vehicle_variant', Headlight::class, 'headlight_product'])->distinct();
}
```

I get the right 567 unique products loaded... except if i replace `->with('products')` by `->withCount('products')`:

```php
VehicleVariant::query()->withCount('products')->find(110275);
```
Here, i still get 826 products in the `products_count` attribute.

Do you have any idea why and how i can fix this?

Thank you very much :)

**Comment by toyi** [comment]
The duplication is caused by the `Product` that are linked to multiple `Headlight` that may also all be individually linked to the  `VehicleVariant`.

Since it gathers all `Product` linked to a `VehicleVariant` through `Headlight`, it makes sense now why a `Product` is sometimes picked up multiple times.

However, i still doesn't understand why  `->with('products')` gathers a Collection with the correct amount of products unlike  `->withCount('products')` (when using `->distinct()` at the end of the relationship).

**Comment by staudenmeir** [comment]
`withCount()` ignores `distinct()`, you need to apply it manually:

```php
VehicleVariant::withCount([
    'products' => function ($query) {
        $query->select(DB::raw('count(distinct products.id)'));
    },
])->find(110275);
```

**Comment by toyi** [comment]
Ok good to know, it works perfectly !

I have not tested it but I guess it is not only ignored in this package but also in other native relationships.

Thank you very much for your quick and helpful answer 🥇

**Comment by staudenmeir** [comment]
Yes, this is native Laravel behavior.
