### ISSUE TITLE
User → has many → Domain → belongs to → Plan

### ISSUE THREAD

**Issue by f-liva** [staudenmeir/eloquent-has-many-deep#99]
Good morning

I am trying to realize the relationship in question, where a `User` has more elements of type `Domain` which in turn belong to a `Plan`.

I can't find the right combination of parameters to make this relationship work.

How would you realize it?

The raw query should be this one:

```sql
select plans.* 
from plans 
inner join domains on domains.plan_id = plans.id
where domains.user_id = [USER_ID]
```

**Comment by staudenmeir** [comment]
Have you tried a native `BelongsToMany` relationship: https://laravel.com/docs/8.x/eloquent-relationships#many-to-many

**Comment by f-liva** [comment]
Yes, there is no user_domain table. The tables are `users`, `domains` and `plans` and I'm trying to use your package to replicate the query I wrote above. Is it feasible?

**Comment by staudenmeir** [comment]
In your case, `domains` is the pivot table.

**Comment by f-liva** [comment]
Ok, thank you!
